### ISSUE TITLE
Investigate odd touch behavior in Chrome Webview on Android 4.4

### ISSUE THREAD

**Issue by dfreedm** [jquery/PEP#135]
@RByers It looks like `touchcancel` is sent immediately after `touchstart` if `preventDefault` isn't called.

**Comment by DimitryDushkin** [comment]
I've faced same problem on stock browser on Android 5.0 on Samsung S4 (com.sec.android.app.sbrowser (34.0.1847.76).
You should call `e.preventDefault()` if you do not want browser to trigger `touchcancel` immediately after `touchstart`. Problem only exists in stock browser and do not reproduces on Android Chrome and any other browser.
I have following head tag:
`<meta name="viewport" content="width=device-width,maximum-scale=1,initial-scale=1,user-scalable=0">`
