### ISSUE TITLE
README: update links to examples

### ISSUE THREAD

**Issue by jzaefferer** [jquery/PEP#147]
These are still pointing at polymer.github.io URLs: https://github.com/jquery/PointerEvents#examples

**Comment by Mottie** [comment]
@kborchers The new links point to non-existent pages.

**Comment by scottgonzalez** [comment]
@Mottie That's probably related to the repo rename that just happened. I'm waiting for the gh-pages to start working before updating them.

**Comment by scottgonzalez** [comment]
For some reason gh-pages doesn't seem to be updating. I'd actually prefer to just delete this for now and recreate the gh-pages once we've done the basic cleanup and have a new build available.

**Comment by scottgonzalez** [comment]
I've filed #156 to track this.
