### ISSUE TITLE
Captured Pointers and elements detatched from dom

### ISSUE THREAD

**Issue by stakach** [jquery/PEP#149]
If a pointer is captured and sending events to a particular element and then the element is detached (possibly also removed however I've only tested this with jquery detach) from the DOM then events are still sent to this element.

However this should not be the case. Detaching elements from the DOM should trigger a capture cancelled.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
