### ISSUE TITLE
Setup weekly meetings

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#155]

**Comment by scottgonzalez** [comment]
Doodle: http://doodle.com/tps8t38cn5pa36ai

Ignore the actual dates, just look at the day of the week and the time.

**Comment by scottgonzalez** [comment]
Wednesday 10:00a ET is the time that works the best for this group. Let's plan on next week, February 4th, being our first weekly meeting since @jacquesperrault and I are still working on our tasks which are likely blocking any other progress right now.

**Comment by scottgonzalez** [comment]
@jacobrossi realized that he forgot to account for time zone differences, so he updated his availability and we now have a better time that will also allow @csnover to attend.

**Meetings will be Thursday at noon ET**

**Comment by csnover** [comment]
TIME ZONES, HOW DO THEY WORK :clap: :)

**Comment by jacobrossi** [comment]
After years of doing international calls in the W3C, I don't know how I
messed this up. :-) But thanks for being flexible!
