### ISSUE TITLE
Re-enable gh-pages after the next build

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#156]
gh-pages currently isn't working for some reason, so I'd like to just delete the branch and recreate later once we've done some basic cleanup. We'll be switching our builds to use AMD (#154) and setting up a new test infrastructure (#153). There's some other general changes that likely need to occur as well. Once all the initial work is done, we should do a release and then recreate gh-pages with the samples using the updated code.

**Comment by kborchers** [comment]
:+1:

**Comment by Mottie** [comment]
You probably just need to push an update to the gh-pages. Looking at the [file page](https://github.com/jquery/PEP/tree/gh-pages) shows the last update was a year ago.

**Comment by scottgonzalez** [comment]
This was done with the 0.3.0 release.
