### ISSUE TITLE
Create release script

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#159]
* [ ] Use [jquery-release](https://github.com/jquery/jquery-release)
* [ ] Publish to jQuery CDN
* [ ] Publish to Bower
* [ ] Publish to npm
* [ ] Update samples in gh-pages

----

Manually register the Bower package after the first release

**Comment by jzaefferer** [comment]
Since `jquery-release` supports it already, we should also publish to npm, e.g. for use with [jspm](http://jspm.io/).

**Comment by nickcolley** [comment]
How about NPM? :+1:

**Comment by scottgonzalez** [comment]
Oh joy. We get to pick a different name for publishing to npm. https://www.npmjs.com/package/PEP shows 404, but https://www.npmjs.com/package/pep exists and I believe there are parts of npm that are case insensitive.

**Comment by csnover** [comment]
just use some homographs. https://www.npmjs.com/package/𝔭𝔢𝔭 anyone?

**Comment by arschmitz** [comment]
https://www.npmjs.com/package/𝔭𝔢𝔭 thats pretty snazzy!

**Comment by jzaefferer** [comment]
Potential npm names:

* pointereventspolyfill
* pointerevents-polyfill
* pointer-events-polyfill
* pepolyfill
* pe-polyfill
* pepjs
* po-ev-po
* poi-eve-pol

**Comment by arschmitz** [comment]
I would pick pepjs all the others seem long, or too abstract to easily remember.

**Comment by scottgonzalez** [comment]
We've settled on pepjs.
