### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#161]
@isaacdurazo Are you interested in this?

**Comment by isaacdurazo** [comment]
@scottgonzalez depending on the deadline :watch: 

I'm pretty busy right now and will probably be available to work on this by the end of March

**Comment by scottgonzalez** [comment]
I think that's fine, especially since we have no other volunteers right now ;-)

We'll likely have some pre-1.0 releases before then, but I don't think we have any urgent needs for the logo.

**Comment by isaacdurazo** [comment]
:+1:

**Comment by stuartpb** [comment]
Thoughts on what the logo would look like? Something like the [HTML5 technology](http://www.w3.org/html/logo/#the-technology) icons? Something like the Bower bird? A mouse with a finger holding a pen?

**Comment by stuartpb** [comment]
Maybe just a riff on the [Pep Boys](https://en.wikipedia.org/wiki/Pep_Boys) logo with a mouse, a finger, and a stylus instead of the faces?

**Comment by csnover** [comment]
An apple stamping on a human face—forever :)

**Comment by jacobrossi** [comment]
Brainstorming....

This has been a popular info graphic used in talks about pointer events. So it has a bit of currency perhaps.I wonder if maybe there's an icon version of this concept without text labels.   ![pointer funnel](http://www.w3.org/TR/pointerevents/pointer.png)

The funnel kind of represents the nature of pointer events consolidating input models into one. It also fits nicely for the polyfill aspect (taking multiple browser APIs and consolidating into one).

**Comment by stuartpb** [comment]
Maybe something like this:

![pep-funnel-logo](https://cloud.githubusercontent.com/assets/572196/7638079/3ab8c72e-fa27-11e4-9c9b-2ac970c98d0d.png)

**Comment by kborchers** [comment]
@isaacdurazo would you want to take a stab at some options?

**Comment by isaacdurazo** [comment]
Yah I think I could take these ideas and turn them in to some logo proposals. I literally had no idea what it could be, so this helps a lot.

**Comment by isaacdurazo** [comment]
Hey guys, just sharing a couple of early ideas:
![x6jkbxrap8uvjcvke-if4q0niuwodjcvh12h9ccqdoq](https://cloud.githubusercontent.com/assets/1379244/7660432/b8a1b150-fafe-11e4-8539-17f6e3f7df69.png)

**Comment by stuartpb** [comment]
Excellent. Of the two, I feel the one on the left is better (more clever suggestion of the pointer-arrow and more closely fitting the W3C visual style).

**Comment by patrickhlauke** [comment]
perhaps a bit too literal, but here's something i cooked up for myself a while ago along those lines...

![pep-logo-outlines](https://cloud.githubusercontent.com/assets/895831/7660758/ef060dea-fb44-11e4-8bb6-d03dc223f982.png)

(actual SVG available if needed)

**Comment by isaacdurazo** [comment]
What do you guys think about something like this?

![screenshot 2015-06-05 12 06 33](https://cloud.githubusercontent.com/assets/1379244/8013111/6726fa3c-0b7b-11e5-97de-bdb60d9aa980.png)

**Comment by rxaviers** [comment]
FWIW, :+1:

**Comment by jdalton** [comment]
So jealous right now.

**Comment by kborchers** [comment]
I think this looks great! :+1:

**Comment by arthurvr** [comment]
This looks soooooo goood :+1:

**Comment by jacobrossi** [comment]
Love it! I think we have a winner. :+1:

**Comment by stuartpb** [comment]
I like https://github.com/jquery/PEP/issues/161#issuecomment-102503480 as an icon for pointer events themselves and https://github.com/jquery/PEP/issues/161#issuecomment-109401366 as a logo for this specific polyfill.

**Comment by scottgonzalez** [comment]
@isaacdurazo The team has agreed to make https://github.com/jquery/PEP/issues/161#issuecomment-109401366 our logo :-)

**Comment by 1j01** [comment]
![](http://i.imgur.com/URaPhbX.png?1)
(Just felt like drawing, don't mind me)

**Comment by isaacdurazo** [comment]
Hey guys, sorry for my late response. I'm glad you liked the logo, one thing I've left to do though is work on the wordmark. I'll work on some explorations and post the results here. If you have suggestions please feel free to post them here as well

**Comment by stuartpb** [comment]
The only thing that comes to mind is matching the blocky HTML5 wordmark (the one that goes above the orange "5" shield).

**Comment by stuartpb** [comment]
Do we have an SVG source for the logo?

**Comment by isaacdurazo** [comment]
Hey guys, just wanted to let you all know that I'm still working on this. 

Due the shape of the logo it's been a little difficult to incoportate the wordmark, so I thought about putting everything within a container (a shield kind of thing in this case).

Here's where I'm at. Keep in mind that this is not done, It still needs lots of polish and I might need to tweak colors and stuff. Thanks for your patience

![screen shot 2015-07-01 at 10 08 42 am](https://cloud.githubusercontent.com/assets/1379244/8460397/3135099c-1fd9-11e5-9ca7-70240d46385b.png)

**Comment by scottgonzalez** [comment]
I really like the direction you're headed with this.

**Comment by arschmitz** [comment]
I like this in the shield

**Comment by jdalton** [comment]
<img src=https://cloud.githubusercontent.com/assets/4303/8460598/ace83144-1fda-11e5-8932-0aaecb85ab21.png height=50% width=50%>

**Comment by dmethvin** [comment]
Theme song is already covered. https://www.youtube.com/watch?v=xoathx1CBEQ

**Comment by stuartpb** [comment]
Nice direction. Perhaps the tops of the "P"s could be level, with the descenders going down to match? Also, and I don't know if this is just an artifact of that being a rough draft, I was hoping for letters that more resemble the HTML5 shield's angular aesthetic.

**Comment by kborchers** [comment]
Anyone have any final thoughts on this so @isaacdurazo can give it final polish? I know this is not high priority but it will definitely help me when talking about and promoting this project and the foundation in presentations so the sooner the better would be great.

In the meantime, does anyone object to me using the logo in Isaac's last comment until one is final just so it's not the only project with a text name? (Other than Isaac whom I assume would object because he wasn't done :wink:)

**Comment by isaacdurazo** [comment]
@kborchers the next step here for me would be to polish this last version and continue iterating a little (but I have been having a few months of lots of work and things on my plate). Most of us seems to like this direction so I don't why not start using what we have until I can make some more progress.

**Comment by jacobrossi** [comment]
Yep, no concerns here.

**Comment by jzaefferer** [comment]
PEP inside shield looks good to me, too. Maybe better to keep the characters on one line, instead of adapting to the props below.

**Comment by jzaefferer** [comment]
@isaacdurazo in your last comment you said the logo still needs polish. Any idea when you might get around to finishing it?

**Comment by isaacdurazo** [comment]
@jzaefferer, sorry I haven't been active. Next week seems more open to me, so I will continue working on it

**Comment by isaacdurazo** [comment]
Hey guys, sorry it took me so long to get back to this. I was just playing around with the last version and this came up

<img width="441" alt="pep" src="https://cloud.githubusercontent.com/assets/1379244/11281892/e7af575a-8eb9-11e5-84b0-17cebffbc8fa.png">

I simplified a lot the graphics and took some elements from the HTML5 logo (including the font). I this one would be great as a sticker, and could be even simplified more when people get's more used to it and be just:
<img width="424" alt="pep-mark" src="https://cloud.githubusercontent.com/assets/1379244/11281955/28a1efac-8eba-11e5-8103-724a3291546d.png">

I would love to know what everyone else thinks.

**Comment by stuartpb** [comment]
I liked them better going into the funnel, honestly.

**Comment by arschmitz** [comment]
i think i agree with @stuartpb i think i like the previous one better

**Comment by isaacdurazo** [comment]
Ok, thanks for the comments. I'll try to incorporate the funnel back into this new direction

**Comment by stuartpb** [comment]
Also, I liked the shading going along the lines (suggesting depth of each line as a cylinder), rather than having all the shadows be straight and vertical.

And, to be more specific about the funnel, one of the main things I liked about it is that it made the image roughly as tall as it is wide, with neither width nor height being disproportionate to the other.

**Comment by isaacdurazo** [comment]
Alright guys, so how about this then? 

I basically brought the funnel and the shading back using the latest colors
![screenshot 2015-12-04 16 30 12](https://cloud.githubusercontent.com/assets/1379244/11603992/6557103a-9aa4-11e5-98cc-c26769f5fc6d.png)

**Comment by roblarsen** [comment]
:+1:

**Comment by rxaviers** [comment]
Awesome

**Comment by arschmitz** [comment]
LGTM

**Comment by bethge** [comment]
Awesome! Where can I get the sticker?

**Comment by arthurvr** [comment]
:heart_eyes: Awesome!

**Comment by isaacdurazo** [comment]
Hey guys,

So here are the the 3 possible versions you might need (Zip folder with EPS files bellow) 

![screenshot 2015-12-08 21 52 34](https://cloud.githubusercontent.com/assets/1379244/11677006/0a3479ae-9df6-11e5-82c1-5925de399a28.png)

[PEP logo.zip](https://github.com/jquery/PEP/files/56361/PEP.logo.zip)

**Comment by jzaefferer** [comment]
#247 adds a 50% scaled down version of the shield version to the readme.
