### ISSUE TITLE
Determine team based on interests

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#162]
Even though we've had a few conversations with various people, teams, and companies, it's not currently clear exactly *how* everyone plans to be involved in PEP. If you plan on being actively involved in this project, please leave a comment describing the types of tasks you're interested in. This can include anything, such as writing documentation, triaging issues, writing patches, reviewing pull requests, testing, etc.

**Comment by csnover** [comment]
I will try to assist with issue triage, cross-project communication and integration on the Dojo side, making any necessary enhancements/fixes to Intern, and consulting on testing/any other technical questions where I can provide useful feedback.

**Comment by arschmitz** [comment]
I'm happy to help with issues, triage, bug fixing, testing ( have the jQuery mobile device lab ), writing code, pretty much anything. Probably not the best person for writing docs though.

**Comment by jacobrossi** [comment]
Provided the CLA goes through (and I'm nearly certain it will), I'm happy to help with issues, triage, bug fixing, writing code, docs, evangelism, etc.  I'm frankly not well experienced with JS test suites and Intern (who needs testing? :-p).  But I'd like to learn.  So expect some hand holding if I work on that area. I expect I can only commit 1-3 hours a week on average, but can invest more time on an as-needed basis for important tasks.

**Comment by cgack** [comment]
I'm happy to help out with anything as much as time allows.

**Comment by roblarsen** [comment]
I'd likely be redundant and/or hard-pressed for time for anything code-related, but I'm happy to help with documentation and the like if there's any need. I've already done a bit of writing about this (Pointer Events vs the current hybrid approach and using the Polymer version of the polyfill) so once the new shape of the project coalesces I'd be happy to write up whatever needed writing up.

**Comment by patrickhlauke** [comment]
I'm also happy to help if I can (probably also more along the lines of documentation).
