### ISSUE TITLE
Button state -1 for no mouse buttons depressed

### ISSUE THREAD

**Issue by bethge** [jquery/PEP#173]
In the Pointer Events spec, [section 5.1.1](http://www.w3.org/TR/pointerevents/#button-states) it says, that if no mouse buttons are depressed, the `button` property of the event is supposed to be -1. If I am not mistaken, PEP currently only passes through the mouse event's `button` value (which is 0).

IE appears to have already extended the button state range to -1, see [IE Dev Center Button Property] (https://msdn.microsoft.com/en-us/library/ie/ff974877(v=vs.85).aspx).

I was wondering if you also intend to implement this behavior. (I believe @steditor hinted at this in #168)

**Comment by Steditor** [comment]
This should be easy to implement with the changes of #168 (it could be a simple reverse mapping from `buttons` to `button`) - we should probably try to make some progress there...
