### ISSUE TITLE
ES3 / attachEvent support

### ISSUE THREAD

**Issue by jzaefferer** [jquery/PEP#174]
We've discussed in the past that we want to support IE8+, but aren't tracking that anywhere. Accordingly I have no idea what issues we have to deal with and what plans we already made. 

As far as I know, one idea was to build a pep-jquery.js that would replace (some of) the event dispatching code with the event abstraction for jQuery. That would bring support for `attachEvent` without adding a lot of overhead (assuming jQuery is required anyway).

Would be great to update this with more details, for anyone interested in working on this.

**Comment by arschmitz** [comment]
@jzaefferer there used to be a repo for this that at a point was working, when it was based on polymer but that seems to be gone now. Probably because I believe we removed the hooks that made it work. It might make sense to open a new repo for it now even if its just for issue tracking.

**Comment by kborchers** [comment]
Like @arschmitz said, this won't work without the hooks that were removed but maybe a good reference for future discussion.

https://github.com/jquery-archive/jquery-pointer-events

Related, I would vote to explore supporting IE9+ here and try to find a way via polyfills, etc to support IE8+ in a different repo.

**Comment by arschmitz** [comment]
It is possible for sure to fix the ES3 issues with polyfills when jquery-pointer-events still worked ( but after all the es5 stuff got added ) I had this working with es5-shim and es5-sham in ie8. I'm +1 for requiring the use of polyfills for this. However I would like us to at least try to reduce it to only needing es5-shim and not es5-sham.

**Comment by jzaefferer** [comment]
We're not supporting IE8.
