### ISSUE TITLE
jquery/PEP vs jquery.pep.js

### ISSUE THREAD

**Issue by thijsBreker** [jquery/PEP#176]
When searching for the pointer events poly-fill I bumped into jquery pep, which apparently does stuff with drag & drop: https://github.com/briangonzalez/jquery.pep.js/ I even initially thought this plug-in by Brian Gonzalez was the poly-fill. This isn't something you guys can help with but I wanted to inform you guys about the existence of this confusingly named plug-in.

I'll also inform Brian Gonzalez, maybe he can mention this polyfill in his readme or something.

**Comment by scottgonzalez** [comment]
Thanks for bringing this up, but I don't think there's anything for us to do. PEP is not a jQuery plugin, so hopefully this won't cause too much confusion.
