### ISSUE TITLE
Suppress over/out/enter/leave during capture

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#177]
Boundary events should only fire when they occur on the boundary of the capturing element. Boundary events from other elements should be suppressed, but they're currently kept and retargeted to the captured element.

**Comment by scottgonzalez** [comment]
Also look into what events are triggered in each browser when the pointer is released over a different element.

**Comment by bethge** [comment]
I made a little visual test: http://jsbin.com/rihoyaqiso and did a 6 step interaction:

1.Enter capturing element 
2. Press left mouse button [start capture]
3. Leave capturing element, enter _other_ non-capturing element 
4. release left mouse button
5. move mouse
6. leave _other_ element

The interesting parts are steps 3, 4 and 5.

Browser | Leave capturing, enter _other_ | release lmb | move mouse
 ---------|----------------------------------|--------------|---------------
_Win10 VM with IE11 w/o PEP_ | `pointerout` >> `pointerleave` >> `pointermove`+ | `pointerup` | `pointermove`* >> `pointerover`* >> `pointerenter`* >> `pointermove`*+
_Chrome 42 w/ PEP_| `pointerout` >> `pointerleave` >> `pointerover` >> `pointerenter` >> `pointermove`+ | `pointerup` >> `pointerout`* >> `pointerleave`* | `pointerover`* >> `pointerenter`* >> `pointermove`*+
_FF 37 w/ PEP_ | `pointerout` >> `pointerleave` >> `pointerover` >> `pointerenter` >> `pointermove`+ | `pointerup` | `pointermove`*+ 
_Safari 8.0.5 w/ PEP_| `pointerout` >> `pointerleave` >> `pointerover` >> `pointerenter` >> `pointermove`+ | `pointerup` | `pointermove`*+ 

 `*` : Events triggered on other element.

On releasing the lmb on Chrome, a mouseout is fired which causes the pointerleave and pointerout.

After having released the lmb, the next events fire on the _other_ element. For e.g. a pointermove the spec demands a pointerenter and pointerover beforehand on the same element, which do not happen on FF and Safari.
IE11 with native PE holds back on the pointerenter and pointerover for the _other_ element until the capture is released and the first move/up/down event triggers.

Iiuc, pointerover and -enter on the _other_ element need to be delayed, until after the release of the capture and a move/up/down on the _other_ element occurs. Alternatively, pointerover and -enter on the _other_ element are suppresed and pointermove, -up and -down need to validate that a pointerenter and -over has occurred.

_[Todo]: Test on IE10_

**Comment by scottgonzalez** [comment]
I've started a thread on public-pointer-events to see if we can get the expected events documented. I have a feeling that without this discussion, Firefox would end up with different behavior than IE (see details in the thread).

**Comment by stuartpb** [comment]
Perhaps a clone of [fireEvent](https://github.com/jquery/PEP/blob/da854e479653a6ac367a3f031568923e09871a2e/src/dispatcher.js#L258) in the dispatcher like fireOwnEvent that only fires an event if there is no pointer capture / the capture target is the same as the original event target?

**Comment by stuartpb** [comment]
Also, pointer capture and event firing should kind of be rewritten to process pointer capture at the point *of the next event*, per http://www.w3.org/TR/pointerevents/#firing-events-using-the-pointerevent-interface
