### ISSUE TITLE
DON'T CLOSE IMPORTANT PULL REQS!!!! :hankey:

### ISSUE THREAD

**Issue by supergray** [jquery/PEP#178]
https://github.com/jquery/PEP/pull/171. by locking the pr @scottgonzalez does not even give me a voice anymore. rude guy.

**Comment by scottgonzalez** [comment]
Did you have something meaningful to contribute? I'm not sure what you're trying to accomplish with this issue.

**Comment by supergray** [comment]
You mean I don't contribute? You're such a jerk. I want me PR to be merged, that's what I try to accomplish. @jquery can we remove this committer, he's rude to me.
