### ISSUE TITLE
On "pointerup" event, "pressure" must be zero

### ISSUE THREAD

**Issue by compulim** [jquery/PEP#180]
Tested on Chrome 42 on Windows with mouse, and also Safari on iOS 8.2 on iPad. The "pointerup" event emit a PointerEvent of pressure 0.5, instead of 0.

When testing the same code under IE11 with mouse (with or without PEP), the "pointerup" event give pressure of 0.

**Comment by appsforartists** [comment]
Here are the relevant bugs against Chrome and against the spec:

- https://crbug.com/648777
- https://github.com/w3c/pointerevents/issues/146/

As you can see from this chart, PEP currently does the wrong thing on iOS but the right thing on desktop:

| Platform      | Browser        | Pointer      | pointerup pressure is 0 | pointerup pressure is whatever the last pointermove recorded  |
| ------------- | -------------- | ------------ | ----------------------- | ------------------------------------------------------------  |
| Android       | Chrome         | touch        |                         | :ballot_box_with_check:                                       |
| iOS           | Safari via PEP | touch        |                         | :ballot_box_with_check:                                       |
| Mac           | Chrome         | trackpad     | :ballot_box_with_check: |                                                               |
| Mac           | Chrome         | Wacom stylus | :ballot_box_with_check: |                                                               |
| Mac           | Chrome         | Wacom touch  |                         | :ballot_box_with_check: (always 1, spec says it should be .5) |
| Mac           | Firefox        | trackpad     | :ballot_box_with_check: |                                                               |
| Mac           | Firefox        | Wacom stylus | :ballot_box_with_check: |                                                               |
| Mac           | Firefox        | Wacom touch  | :ballot_box_with_check: |                                                               |
| Mac           | Safari via PEP | trackpad     | :ballot_box_with_check: |                                                               |
| Mac           | Safari via PEP | Wacom stylus | :ballot_box_with_check: |                                                               |
| Mac           | Safari via PEP | Wacom touch  | :ballot_box_with_check: |                                                               |
| Windows       | Chrome or Edge | touch        |                         | :ballot_box_with_check:                                       |
| Windows       | Chrome or Edge | trackpad     | :ballot_box_with_check: |                                                               |
| Windows       | Chrome or Edge | stylus       | :ballot_box_with_check: |                                                               |
| Windows       | Firefox        | touch        | :ballot_box_with_check: |                                                               |
| Windows       | Firefox        | trackpad     | :ballot_box_with_check: |                                                               |
| Windows       | Firefox        | stylus       | :ballot_box_with_check: |                                                               |

**Comment by appsforartists** [comment]
Chrome is [fixing their behavior](https://bugs.chromium.org/p/chromium/issues/detail?id=648777&desc=4#c10).  When #313 lands, this will be consistent in every case I've seen (except for touch on Windows)! 🎉
