### ISSUE TITLE
"pointerType" should always be "touch" when polyfilling on iOS

### ISSUE THREAD

**Issue by compulim** [jquery/PEP#181]

**Comment by stuartpb** [comment]
Isn't iOS capable of using Bluetooth mice and the like?

**Comment by patrickhlauke** [comment]
no, iOS won't pair with mice or similar alternative pointer devices. only keyboards

**Comment by scottgonzalez** [comment]
@compulim Are you experience situations where it's not touch?

**Comment by compulim** [comment]
I didn't check the latest commit. But at the time I wrote this issue, the pointerType on iOS is always mouse but not "touch". I think should check if it's iOS and assume pointerType is always touch. Since iOS doesn't support mouse currently, touch should be primary input method (a.k.a. a good guess) for all iOS devices.

**Comment by scottgonzalez** [comment]
I haven't been able to reproduce this, and it doesn't make sense that Touch Events would get logged as as mouse. If you can provide a reduced test case that shows the problem, we can investigate, but if not, I don't think there's actually a bug.

**Comment by compulim** [comment]
Fair. Will make a minimal repro.

**Comment by Todberg** [comment]
Is anybody working on this?

**Comment by patrickhlauke** [comment]
seems we've been waiting for a repro example of the issue.

in the meantime, touch events have also added the `touchType` property though, so even on iOS (with the apple pencil) you can have touches that should map to `pen` when `touchType` is `stylus` rather than `direct` https://w3c.github.io/touch-events/#touch-interface

**Comment by patrickhlauke** [comment]
xref https://github.com/jquery/PEP/issues/342

**Comment by patrickhlauke** [comment]
suggest closing this (unless there's a reproducible minimal example of where PEP currently incorrectly doesn't map actual direct touches to `touch`)

**Comment by timFrylinck** [comment]
I noticed that touch events on iOS that occur on overflowing content are recognized by PEP as having a pointerType of "mouse". I created the following CodePen to illustrate the issue:

https://codepen.io/timFrylinck/pen/OZgLpB/

Every time the user taps on the red rectangle it will be correctly recognized as a "touch" pointerType, but tapping on the "Overflowing text" will be incorrectly recognized as a "mouse" pointerType.

The CodePen uses PEP 0.4.3

I am not sure if this relates to this issue or if a new issue should be opened.

**Comment by Ciantic** [comment]
I'm able to reproduce this with simple "pointerenter", then the `console.log("enter", e.originalEvent.pointerType);` in the iPad console gives always "mouse", which is kinda depressing cause that's what I'm trying to distinguish, between computer mouse and iPad touch.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
