### ISSUE TITLE
Spec no longer says Mouse is pointerId 1

### ISSUE THREAD

**Issue by nkronlage** [jquery/PEP#186]
touch.js says:

    // Spec specifies that pointerId 1 is reserved for Mouse.
    // Touch identifiers can start at 0.
    // Add 2 to the touch identifier for compatibility.

But this was later removed from the specification:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=21746

**Comment by nkronlage** [comment]
mouse.js also has code for forcing the id to 1:

    var mouseEvents = {
      POINTER_ID: 1,

It would be best to provide a random number here so apps don't try to use 1 for mouse only to be broken when they no longer need the polyfill.

**Comment by scottgonzalez** [comment]
The comment is no longer accurate, but the implementation is. The current implementation guarantees that no collisions will occur. If we choose a random value, then it slightly complicates the logic for collision prevention. Personally, I don't think it's important for the polyfill to guard against user error here, but I'll wait for us to discuss in today's meeting.

**Comment by scottgonzalez** [comment]
The team doesn't think any change should be made. I'll update the comment after #185 lands.
