### ISSUE TITLE
Inhibiting hold-to-bring-up-context-menu in Chrome (CrOS)

### ISSUE THREAD

**Issue by stuartpb** [jquery/PEP#187]
Right now, even with `touch-action: none` set as an attribute _and_ a CSS rule, touching and holding something causes the page's color to dim and two rings to encircle the touch on Chrome OS. Is there no way this behavior can be prevented?

**Comment by stuartpb** [comment]
cc @rickbyers (the only Chrome dev I know :p)?

**Comment by RByers** [comment]
`touch-action` doesn't influence this on IE either (it's defined to affect only panning and zooming).

IE has a non-standard event for this IIRC (just went searching for it but couldn't find it).  Some MS-prefixed thing you can call preventDefault on to suppress the long-press UI.

You can call `preventDefault` on the contextmenu event to prevent the context menu from showing, but this is too late to disable the UI effect.

Safari also has `-webkit-touch-callout: none` but I'm not sure of the exact behavior of that, and we don't have that in Chrome.

I believe the only way to suppress this in Chrome today is to call `preventDefault` on the touchstart, but that also disables other gestures like scrolling and tapping.  Perhaps the polyfill should implement an event like IE's non-standard one by calling preventDefault on the touchstart?

Feel free to [file](http://crbug.com/) a chromium feature request describing exactly what control you'd need.  We'd have to work on standardizing an API, but if we can get the use cases well justified then it should be possible.  Eg. do you need to disable the long-press gesture entirely, or just the affordance (with the existing independent controls for disabling the context menu and text selection)?  What exactly is the relationship to existing features in other browsers.

**Comment by stuartpb** [comment]
> `touch-action` doesn't influence this on IE either (it's defined to affect only panning and zooming).

Well then, that strikes me as a failure on IE's part to properly implement the `touch-action` specification, which states that "Touches that begin on the element **`MUST NOT`** trigger default touch behaviors." I don't see how context menus aren't "default touch behaviors".

Since this is a touch behavior common to IE and Chrome (and IOS Safari, FWIW), I would say the `touch-action` specification needs to be amended to recognize values opting in to non-manipulation touch behaviors.

**Comment by stuartpb** [comment]
I'll start a topic for exended values of `touch-action` on https://discourse.wicg.io/ later today.

**Comment by RByers** [comment]
Yeah that's a possibility probably worth discussing.  There annoying ambiguity here due to legal issues about what the pointer events spec can and cannot say around "gestures".  But the intention of touch-action was to impact only the behavior of gestures implemented off the main thread (panning and zooming).  But that's not to say it can't evolve to do more (but there are some disadvantages relative to just defining a new API).

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
