### ISSUE TITLE
"lostpointercapture" doesn't fire when releasing multiple pointer captures

### ISSUE THREAD

**Issue by stuartpb** [jquery/PEP#188]
Tested on my Acer C720P Chromebook, by touching two elements that setPointerCapture on pointerdown, and trust implicit pointer release for losing the capture - note how after "up", "out", and "leave", lostpointercapture does not fire for pointerId 3:

```
pointerover 2
pointerdown 2
gotpointercapture 2
pointerover 3
pointerdown 3
gotpointercapture 3
pointerout 2
pointerleave 2
pointerover 2
pointerenter 2
pointerout 3
pointerleave 3
pointerover 3
pointerenter 3
pointerup 2
pointerout 2
pointerleave 2
lostpointercapture 2
pointerup 3
pointerout 3
pointerleave 3
```

**Comment by stuartpb** [comment]
This was on two SVG paths, if it matters (#134).

**Comment by stuartpb** [comment]
Also, it appears to be actually not releasing the pointer capture, beyond just not firing the event.

**Comment by stuartpb** [comment]
The logic in https://github.com/jquery/PEP/blob/da854e479653a6ac367a3f031568923e09871a2e/src/dispatcher.js#L308-310 looks bugged. It's setting a listener across the *entire document* to release the pointer capture when *any* pointer is released? And it's only tracking *one* implicit release across the *entire dispatcher*?

**Comment by stuartpb** [comment]
And shouldn't `captureInfo` (which would more clearly be named `pointerCaptureTargetOverrides` to match the spec) be a PointerMap? And why is there a `PointerMap` instead of just using a polyfillable `Map`?

**Comment by stuartpb** [comment]
It seems to me that implicit pointer cature release checks would make more sense as part of the dispatchers around https://github.com/jquery/PEP/blob/da854e479653a6ac367a3f031568923e09871a2e/src/dispatcher.js#L162 and https://github.com/jquery/PEP/blob/da854e479653a6ac367a3f031568923e09871a2e/src/dispatcher.js#L182, checking for a pointer capture target override and *then* releasing the capture.

**Comment by stuartpb** [comment]
I submitted #190 to address the PointerMap concern, and am currently rewriting the dispatcher's implementation of pointer capture to address the original issue (as well as #177, potentially).

**Comment by stuartpb** [comment]
I've been working on non-pointer-oriented projects for the last three months - I'm drifting back into pointer-oriented projects now, so I'm putting this back on my plate.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
