### ISSUE TITLE
Revisiting HAS_TOUCH_ACTION_DELAY

### ISSUE THREAD

**Issue by stuartpb** [jquery/PEP#191]
https://crbug.com/329559 as referenced at https://github.com/jquery/PEP/blob/master/src/touch.js#L18 has been superseded by discussion/implementation of the "scroll-blocks-on" property (https://crbug.com/347272). I'm not sure how all this shakes out, in relation to touch-action &c, but it seems like it's something that's moving with Chromium.

**Comment by jacobrossi** [comment]
I believe this idea (scroll-delay, scroll-blocks-on) has been abandoned for various reasons. I don't think it's being pursued any longer.

**Comment by stuartpb** [comment]
> I don't think it's being pursued any longer.

https://crbug.com/489802 (2 hours ago) would indicate otherwise.

**Comment by scottgonzalez** [comment]
@rbyers @azakus Do you have any input on what we should be doing here? Do we need more discussion in PEWG or TECG?

**Comment by RByers** [comment]
We do still want to enable non-scroll-blocking input (touch, wheel, etc.) events in Chromium (http://crbug.com/489802 is the right specific item to track - I separated it out of the larger discussion around scroll-blocks-on).  But the API may be different from what we've previously proposed, and it's not yet clear whether we'll be ready to ship it before we ship pointer events (we should be - it's much simpler, but it'll depend on the standardization process).  

For PEP I'd just remove any code / comments that refers to TOUCH_ACTION_DELAY.  This is obviously still taking awhile to figure out (and isn't the top priority for us).  I'll be sure to involve you guys when we have a specific proposal / prototype to experiment with and debate.

**Comment by RByers** [comment]
By the way, we talked about this general issue (in the context of wheel events) in PEWG here: https://lists.w3.org/Archives/Public/public-pointer-events/2015AprJun/0042.html.  The issue (and so any solution) is largely the same between touch and wheel events.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
