### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by stuartpb** [jquery/PEP#192]
There are a bunch of tests failing in core right now, most (all?) of which seem to be predicated on testing for MSPointerEvent stuff in Internet Explorer that's not there any more.

My plan is to remove the failing tests for now, possibly replacing them with not-broken equivalents at a later date.

**Comment by jzaefferer** [comment]
@stuartpb any chance you're going to work on this in the near future?

**Comment by jzaefferer** [comment]
Looks like there's failures due to missing `ms` property on IE11, and missing requestAnimationFrame on IE9.

**Comment by bethge** [comment]
Should we run the tests against IE11? With IE11 having full Pointer Event support, any failures would highlight differences between our tests' assumptions and IE11's implementation of Pointer Events (which can be valuable), but would not actually test PEP.

More generally: Should we run the tests against browsers with native `window.PointerEvent` support?

**Comment by scottgonzalez** [comment]
Ideally we get to the point where we run the full W3C test suite, which is what browser vendors use to verify their own behavior. So there's no need to check if we're getting different results for native vs. PEP because they should *all* be running and passing the same tests.
