### ISSUE TITLE
Wire up PointerEvent.pressure support for iOS Force Touch

### ISSUE THREAD

**Issue by jacobrossi** [jquery/PEP#194]
Looks like we can possible get these values from [MouseEvent.webkitForce](https://developer.apple.com/library/prerelease/mac/documentation/AppleApplications/Conceptual/SafariJSProgTopics/Articles/RespondingtoForceTouchEventsfromJavaScript.html#//apple_ref/doc/uid/TP40016162-SW1).

Documentation is not clear on what the value type, range, and expected values are. So some testing might be necessary to figure out the mapping. But otherwise, seems more or less straightforward.

**Comment by appsforartists** [comment]
I think this is a stale issue.  In [this test](https://codepen.io/appsforartists/full/gwLWVE/), I'm seeing pressure from PointerEvents in Safari for iOS on an iPhone 6S+.

**Comment by patrickhlauke** [comment]
yes, this should now be closeable
