### ISSUE TITLE
Can I use PEP without polluting the global namespace?

### ISSUE THREAD

**Issue by mramato** [jquery/PEP#198]
I work on a fairly popular [mapping library](https://github.com/AnalyticalGraphicsInc/cesium) that suffers greatly from the fragmented state of input interaction in web browsers.  I would love for us to use PEP to solve our problems, however we have a policy where our library should not modify the global namespace.  Is it possible to require in pep.js as an amd module to avoid this? My initial tests seem to say no.

I'm willing to modify the code if needed to make it happen, but I wanted to get an official response to make sure I wasn't wasting my time (and to see if anyone was interested in a pull request if changes are indeed needed)

**Comment by scottgonzalez** [comment]
Can you explain what pollution you're seeing?

**Comment by mramato** [comment]
My question might not make any sense for PointerEvent, but for example, the fact that `window.PointerEvent` is undefined before requiring in PEP and defined after the fact.  Obviously this is the intended behavior for a polyfill, but I was wondering if it's possible to avoid it.  The goal is that there are no external prototype/object changes caused by simply including our library into an app.

A similar example would be if I wanted to polyfill `string.codePointAt`, I wouldn't actually modify the prototype, instead I would create a module that uses the native codePointAt if it exists, but otherwise use the polyfill code.  Like I said, this kind of use case may not work for PointerEvent.

**Comment by scottgonzalez** [comment]
> The goal is that there are no external prototype/object changes caused by simply including our library into an app

Why? Either you should require that `PointerEvent` support exists, or you should provide the polyfill if necessary. The choice is based on what you're building. But creating a partial polyfill is not a goal of this project.

> A similar example would be if I wanted to polyfill string.codePointAt, I wouldn't actually modify the prototype, instead I would create a module that uses the native codePointAt if it exists, but otherwise use the polyfill code.

That wouldn't really be a polyfill, that's just be equivalent functionality created as a function.
