### ISSUE TITLE
can't move on css transformed element (chrome touch)

### ISSUE THREAD

**Issue by atom-project** [jquery/PEP#200]
With chrome touch emulation and chrome android there is a problem where we can't catch the pointermove event. the element has a css transform property and PEP does not fire pointermove until the dom is refreshed (window resize, element move with chrome dom explorer, ...). 

Safari (ipad and osx) and IE11 (surface) works. Chrome without touch emulation too.

Here is a little fiddle: http://jsfiddle.net/tfbLyqok/5/

thanks

**Comment by codeonpaper** [comment]
I can reproduce the same problem. It seems that this only appears with Google Chrome's touch.

To reproduce this behaviour:

1) Add en element outside from the viewport.
2) Add the ```pointermove``` event on the element.
3) Move the element into the viewport.

After that, the ```pointermove``` will not fire correctly. It fires when you click on it without moving the finger but only once and in a wrong order:

```
pointermove
pointerdown
pointerup
```

**Comment by arschmitz** [comment]
@codeonpaper  @atom-project So this is only a problem when the touch events are emulated? can you reproduce this in any situation a real user would run into?

**Comment by roblarsen** [comment]
@arschmitz  It's a legit problem. I just tested it in Chrome/Android and it fails. 

It works on the stock Android browser on my HTC One.

**Comment by arschmitz** [comment]
@roblarsen Thank you for confirming the description made it sound like this was only a problem with emulators.

**Comment by jzaefferer** [comment]
I can reproduce this using touch event emulation in Chrome on OSX. Might be difficult to fix, but patches are welcome.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
