### ISSUE TITLE
Validity

### ISSUE THREAD

**Issue by vxsx** [jquery/PEP#209]
The polyfill requires touch-action attribute, but sadly that breaks HTML validation. I know it may not matter to most people, but still. It would be great if it would be possible to use `data-touch-action` attribute instead / as well.

**Comment by jzaefferer** [comment]
See #151

**Comment by patrickhlauke** [comment]
I agree though that, in the meantime, switching to `data-touch-action` will at least pass validation and signal that the attribute is used specifically for some 
> custom data private to the page or application

http://www.w3.org/html/wg/drafts/html/master/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes

**Comment by stuartpb** [comment]
Last time I checked, "validity" has been an obsolete concept ever since the HTML5 spec was adopted. The new rule is "everything has some valid interpretation, and the only validity is if it doesn't yield the DOM content you want."

**Comment by stuartpb** [comment]
Moreover, I think there's a implicit understanding (which may be explicitly codified in one of the current W3C draft specs) that *all* attribute names containing hyphens are reserved for content behaviors (with the exception of `data-` attributes which have the single additional property that they are exposed via the element's `dataset` property). This is the same rule that governs element names for the Web Components spec.

**Comment by stuartpb** [comment]
In other words, when it comes to concepts like "validity" and "conformance":

https://31.media.tumblr.com/55d170c898b240783dc332124bbd197d/tumblr_inline_n4foafra0C1sew80h.jpg

http://www.w3.org/html/landscape/#differences-between-whatwg-html-ls-and-w3c-html-5.1

**Comment by FinalAngel** [comment]
:+1: for validation, it also helps on automation processes such as:

```
validate a PR or Project against the W3C Validator and throw an error if it doesn't pass
```

**Comment by stuartpb** [comment]
And, to my point, when it comes to validation, "passes the W3C Validator" doesn't actually get you anything - you can forget to include *all the content between `<body>` and `</body>`* and a validator is going to tell you that your page is just fine. That doesn't mean it's not going to break because you left out your script dependencies.

If you're going to do testing, it needs to be based on the *actual recognized content of the page as parsed in the DOM*, not some pedantic syntax-checker's outdated notions of what browsers "should" accept.

**Comment by jzaefferer** [comment]
Markup validation is just another tool like jshint or jscs. Doesn't tell you if your program works, but it helps find issues. And HTML5 can we validated nicely enough, e.g. using https://validator.github.io/validator/  (to which I happen to provide a [grunt wrapper](https://github.com/jzaefferer/grunt-html)).

**Comment by arschmitz** [comment]
At this point validity of the `touch-acction`attribute is a non issue we are switching to use `touch-action` within the style attribute.

**Comment by vxsx** [comment]
Alright, then I'm closing since it's not relevant anymore. Thanks everyone.
