### ISSUE TITLE
README still lists `touch-action="scroll"` option

### ISSUE THREAD

**Issue by msegado** [jquery/PEP#210]
README.md still contains a reference to the now-removed `scroll` option": 
> * Can also have the value `pan-y pan-x` or `scroll`

Ideally it would also mention the now-allowed `auto` value, event if it doesn't do anything special =)

**Comment by scottgonzalez** [comment]
We should remove the list of values and just link to http://www.w3.org/TR/pointerevents/#the-touch-action-css-property.

**Comment by arschmitz** [comment]
@scottgonzalez do you think we should have the basic usage section at all other then to say to put the prop in the style attribute even the event list we could just point to http://www.w3.org/TR/pointerevents/ , which has everything. I mean we ARE a polyfill.

**Comment by scottgonzalez** [comment]
Yeah, we can gut that and link to specs + examples.

**Comment by msegado** [comment]
Seems like a good idea! Just need to make sure to fill out the "limitations" section as needed.

**Comment by jzaefferer** [comment]
Remove list, replace "touch-action attribute" with the w3c link.
