### ISSUE TITLE
Add method to update current elements with touch-action

### ISSUE THREAD

**Issue by arschmitz** [jquery/PEP#212]
As discussed in the meeting today the lack of support for mutation observers means that on some popular platforms like android < 4.4 and IE9 only elements containing touch-action when the page loads will receive pointerEvents.

To me this seems like a deal breaker for a lot of SPA's. I looked at polyfills and from what i can see the only one that works on android is super heavy handed ( does dom diffing in a recursive setTimeout ) 

I think a compromise is if we provided a method that forced pep to update its bindings. Then this could be called when the dom is update ( when the mutation observer would normally be triggered ).

**Comment by arschmitz** [comment]
Discussed in the meeting today we I will work on adding this when I address #151 and switch to use css.

**Comment by jzaefferer** [comment]
@arschmitz :facepunch:

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
