### ISSUE TITLE
PEP and iframes

### ISSUE THREAD

**Issue by DavidAustin** [jquery/PEP#216]
I'd really like to use PEP with iframes, but it doesn't seem easy.  I guess one option is to load
pep.js in the iframe, but that seems like quite a lot of overhead.  Ideally, I'd think there
should be a method similar to applyPolyFill that takes a window argument.

**Comment by scottgonzalez** [comment]
I'm not sure that this is common enough for us to worry about while we have so much other work to do right now. We can certainly accept a pull request and do a review, but I'm going to close this for now since I don't think the team will work on it.
