### ISSUE TITLE
Click auto insert and draggable disappear 

### ISSUE THREAD

**Issue by stealthbomb** [jquery/PEP#218]
I have a list of widgets that can be cloned and dragged to droppables, hence one can drag many instances of a widget to droppables via cloning.
This works 100%, my only problem is:
When you don't click and hold the original widget to drag, but only click it once Pep then auto inserts the widget into the first droppable container and then the original draggable widget disappears from the list.
The original widget must always stay in the list and Pep must not auto insert it, how do I stop this behaviour?

**Comment by scottgonzalez** [comment]
I'm really unsure what you're referring to. PEP does no insertion, dragging, cloning, etc. Please provide a reduced test case showing the problem and clearly describe why you think PEP is the cause of your issue.

**Comment by arschmitz** [comment]
@stealthbomb i believe your looking for https://github.com/briangonzalez/jquery.pep.js/

**Comment by stealthbomb** [comment]
Awesome, 2 unrelated projects with the same name, dont know how I missed it, sorry, will go place the issue there.
