### ISSUE TITLE
Remove vacuumTouches

### ISSUE THREAD

**Issue by stuartpb** [jquery/PEP#219]
I can't find any documentation for the issue [this code](https://github.com/jquery/PEP/blob/master/src/touch.js#L233-L252) is supposed to fix (the change was introduced in #31 with no prior discussion linked), and it seems like a potentially hindering piece of code (it sounds like it's trying to remove any touch that's currently in progress).

**Comment by arschmitz** [comment]
@stuartpb i was not involved in this particular piece of code but i have run into this issue working with touch events previously. Ill see if i can find the issue for reference.

**Comment by jzaefferer** [comment]
@arschmitz can you look into this again?

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
