### ISSUE TITLE
how to replace javascript event handler to pep handler

### ISSUE THREAD

**Issue by kirantpatil** [jquery/PEP#220]
Hi,

I have js code as below to handle click, mouseover, mouseout events.
       rect = svgdoc.getElementById("slot");
      1)    rect.addEventListener("mouseover", callback1, false);
       2)   $(rect).off().one('click', callback);

How should I replace them with PEP ?

Thanks.

**Comment by patrickhlauke** [comment]
I'm not sure if the issue tracker here is meant to be used for help/support questions, but in general, without seeing the rest of your code, it should be a simple matter of replacing `mouseover` with `pointerover`

**Comment by kirantpatil** [comment]
I  replaced as per your suggestion and it did not work.

**Comment by scottgonzalez** [comment]
Without a reduced test case, there's not much we can do.

**Comment by kirantpatil** [comment]
ok thanks.
