### ISSUE TITLE
pepjs npm package is unusable

### ISSUE THREAD

**Issue by WestonThayer** [jquery/PEP#223]
https://www.npmjs.com/package/pepjs

The package seems to just be a clone of this git repo. If I wanted to use pepjs in my application, I would either have to:

1) Build pepjs as part of my build, or
2) Configure something like browserify to understand ES6 `import` and directly reference `pointerevents.js`

It would be much more helpful if the pepjs npm package simply contained a copy of https://code.jquery.com/pep/0.3.0/pep.js. It's CommonJS compatible, so it can be easily incorporated without having to use option 1 or 2.

I'd be happy to submit a pull request fixing this for package.json, but wanted to check here first to ensure that I'm not off-base with this issue.

**Comment by scottgonzalez** [comment]
That package is supposed to contain the `dist` directory (see [the tag](https://github.com/jquery/PEP/tree/0.3.0/dist)). I'm not sure why that isn't included in the npm install.

The `main` field has already been updated to point to the built file (see 19122a3714621e4b1df2cf6522e6da3f19470387).

Other than figuring out why the `dist` directory isn't included, is there anything else that needs to happen?

**Comment by jzaefferer** [comment]
See #224 for a fix.

**Comment by Cryclops** [comment]
Fantastic, thank you!
