### ISSUE TITLE
Compiled PEP does not work in Firefox

### ISSUE THREAD

**Issue by JurajKavka** [jquery/PEP#227]
Yesterday, i have compiled PEP with Grunt.   

Code below does not work in Firefox (41.0.2)
- in normal desktop mode. 
- in device mode (ctrl+shift+m) when the "Simulate touch events" is disabled.

In both modes, only "pointermove" event is raised. The "pointerdown" event is raised only once,  with the first click after the page load.
  
Code below works properly
- in Firefox (41.0.2) in device mode (ctrl+shift+m), when the "Simulate touch events" is enabled.
- in Chrome (46.0.2490.80) in every its modes (desktop mode, device mode in DevTools)

```HTML
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Timeline UI</title>
</head>
<body>
<div id="test-pep" style="width: 100px; height: 100px; background-color: black;" touch-action="none"></div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="PEP/dist/pep.min.js"></script>

<script>
    $(document).ready(function() {
      var pokEl = document.getElementById('test-pep');
      console.log(pokEl);
      pokEl.addEventListener('pointerdown', function(e){console.log('pointer down')});
      pokEl.addEventListener('pointerup', function(e){console.log('pointer up')});
      pokEl.addEventListener('pointermove', function(e){console.log('pointer move')});
    });
</script>


</body>
</html>
```

When I use recommened way to link pep.js

```HTML
<script src="https://code.jquery.com/pep/0.3.0/pep.js"></script>
```

in mentioned Firefox everything works as expected. 

I have never compiled anything with grunt. Maybe the error was somewhere there :) 

Thank you. J.

**Comment by jzaefferer** [comment]
There've been [22 commits to master](https://github.com/jquery/PEP/compare/0.3.0...master) since that release, so there's plenty room for regressions. That said, I can't reproduce the issue in Firefox 41 on OSX. All tests pass, your script works fine.

**Comment by scottgonzalez** [comment]
This is working properly for me as well. With multiple people that can't reproduce, there's nothing we can do. If you're able to track down any more details, please just leave another comment in this issue.
