### ISSUE TITLE
`grunt test` fails to run intern task

### ISSUE THREAD

**Issue by jzaefferer** [jquery/PEP#229]
I'm not sure what's going on here:
```
$ grunt test
Running "pretest" task

Running "intern:pointerevents" (intern) task
Listening on 0.0.0.0:9000
Starting tunnel...
Error: [POST http://localhost:4444/wd/hub/session] connect ECONNREFUSED
Error: connect ECONNREFUSED
  at exports._errnoException  <util.js:746:11>
  at TCPConnectWrap.afterConnect [as oncomplete]  <net.js:1010:19>

>> TOTAL: tested 0 platforms, 0/0 tests failed; fatal error occurred
Warning: Error: [POST http://localhost:4444/wd/hub/session] connect ECONNREFUSED
Error: connect ECONNREFUSED
  at exports._errnoException  <util.js:746:11>
  at TCPConnectWrap.afterConnect [as oncomplete]  <net.js:1010:19> Use --force to continue.
```
Readme and Contributing.md don't say anything about running tests, and since `npm test` runs `grunt test`, I don't think I'm doing anything wrong.

**Comment by scottgonzalez** [comment]
You need to install [ChromeDriver](http://chromedriver.storage.googleapis.com/index.html?path=2.20/) and then run `chromedriver --port=4444 --url-base=wd/hub` before running the tests.

We should probably have the `test` task check if ChromeDriver is installed. If it isn't, we should show a useful message telling the user where to download it. If it is, we should start it.

**Comment by jzaefferer** [comment]
Yeah, that and mention it in the readme.

**Comment by jzaefferer** [comment]
Got it working with that:
```
>> TOTAL: tested 1 platforms, 10/41 tests failed (1 skipped)
```
Are the 10 failures expected?

**Comment by jzaefferer** [comment]
For the failing tests, see #192.

**Comment by scottgonzalez** [comment]
This has been addressed now that we automatically start ChromeDriver.
