### ISSUE TITLE
All functional tests timing out

### ISSUE THREAD

**Issue by jzaefferer** [jquery/PEP#231]
This is separate from #229 and #192: All functional tests fail with a ScriptTimeout. Happens for me locally using ChromeDriver, can also be observed on Travis, for example https://travis-ci.org/jquery/PEP/builds/88141732

I couldn't find a single revision with passing functional tests.

**Comment by jzaefferer** [comment]
Or a single successful Travis build.

**Comment by bethge** [comment]
I ran the functional tests locally with a selenium-standalone-server + ChromeDriver and all the functional tests were successful.
Iiuc, for the Travis build only the IEs fail, [Chrome][1] and [Firefox][2] pass.

[1]:https://travis-ci.org/jquery/PEP/builds/88141732#L138
[2]:https://travis-ci.org/jquery/PEP/builds/88141732#L883

**Comment by scottgonzalez** [comment]
@jzaefferer You seem to be the only one experiencing this problem locally. Ping me and we can try to figure out what's going on.

**Comment by jzaefferer** [comment]
> selenium-standalone-server

I only ran them with ChromeDriver. Would be nice to have a consistent setup that doesn't require the developer to manually install and run additional tools.

I'll close this and test again once #244 is addressed (or at least has a PR).

**Comment by jzaefferer** [comment]
Also 28a8a417b6783c62579f6384d82e02eecf963275 needs to be reverted.

**Comment by scottgonzalez** [comment]
> Also 28a8a41 needs to be reverted.

Done.
