### ISSUE TITLE
Refactor event cloning and creation

### ISSUE THREAD

**Issue by jzaefferer** [jquery/PEP#235]
Why make an event writeable (dispatcher.cloneEvent) to then create a new event (dispatcher.makeEvent)? This seems to be a lot of unnecessary work (and code), just [to create a writable event](https://github.com/jquery/PEP/blob/1c93f075d7fd04e3c55221a44a3fb40e2a1c2b4e/src/dispatcher.js#L275-L298) which is then [used to a create a new event](https://github.com/jquery/PEP/blob/1c93f075d7fd04e3c55221a44a3fb40e2a1c2b4e/src/dispatcher.js#L249-L261). Both of those functions have a lot of dependencies, so there's a lot more than those 23 and 12 lines of code involved.

In addition, `mouse.js` duplicates the wrapper around `preventDefault()`, for no good reason as far as I can tell.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
