### ISSUE TITLE
Events fail to fire in Chrome when using a laptop touchscreen

### ISSUE THREAD

**Issue by csuwildcat** [jquery/PEP#241]
I recently pulled PEP into X-Tag to take the place of Hand.js, and ran into a strange issue. Every other browser I have tested works fine as long as I am using a mouse, but in Chrome Desktop, no events are fired when using my laptop touchscreen. Chrome Mobile on Android works fine, touches fire events there. I haven't tracked down the offending code in PEP, but can verify it is not being blocked by anything in X-Tag.

I will post back if I can located the code in PEP responsible for the Chrome Desktop event drops.

**Comment by patrickhlauke** [comment]
I can't seem to reproduce this problem. Running http://patrickhlauke.github.io/touch/pep/tracker/tracker-just-pointer-pep.html on my Surface 3 and my (rather ancient) Asus touchscreen laptop (both with Windows 10) with Chrome works fine.

Did you, by any chance, disable touch events in chrome://flags#touch-events ? (though that would also render any code reliant on `touchstart` etc non-working...

**Comment by csuwildcat** [comment]
Let me double check (I did check my dev tool settings, but maybe I missed
this)

**Comment by csuwildcat** [comment]
Wow, definitely a Chrome issue, nothing to do with PEP - get a load of this:

- When I double checked my touch-events flag, it was set to the default `Automatic`
- Just for kicks I set it to be explicitly forced via `Enabled` instead of the default
- When I restarted Chrome, all touchscreen events fired
- So I could run through to confirm the flow, I reset the flag to the default, `Automatic`, and restarted Chrome
- Confusingly, touch events still fired and worked fine...

...so I thought about it and had a hunch, which unfortunately turned out to be right:

I realized that when I restarted Chrome after changing the flag both to `Enabled` and back to `Automatic`, I was disconnected from my monitors with the laptop's screen open the whole time. I repeated the process of restarting Chrome under the `Automatic` option, but this time connected to my monitors - guess what: Chrome's `Automatic` default fails to detect touch capability of the device's native screen when it is launched while connected to external monitors, and never retests, which effectively deadens your entire device to touch events for the duration of Chrome's process existence. Sigh.

Chrome probably isn't listening to the right APIs in Windows that inform it when the laptop screen opens, or when the devices is connected/disconnected to monitors. I will reach out to my contacts at Google to get this addressed - do you want me to leave this ticket open so they have a reference and others can see what is going on?

**Comment by jacobrossi** [comment]
Tagging in @rickbyers on the Chrome team as fyi

But yeah, we should probably close this given it's not a PEP issue.

**Comment by csuwildcat** [comment]
@jacobrossi @rickbyers I have pasted the explanation and repro steps in a Chrome ticket that appears to highlight the same issue. Folks on the ticket were still trying to figure out what was doing it, so I hope this helps: https://code.google.com/p/chromium/issues/detail?id=176058

**Comment by scottgonzalez** [comment]
I'm going to close the ticket based on all the information above. But the fact that PEP has uncovered this odd behavior in Chrome seems like a win to me :-)

**Comment by patrickhlauke** [comment]
> Chrome's Automatic default fails to detect touch capability of the device's native screen when it is launched while connected to external monitors, and never retests, which effectively deadens your entire device to touch events for the duration of Chrome's process existence

Yes, that's my understanding of Chrome's behavior...has been like that for as long as I can remember: it only checks once when the process is first started /cc @rbyers

**Comment by RByers** [comment]
Yeah this is [a know issue](https://code.google.com/p/chromium/issues/detail?id=392584).  Even if we did detect the change, we can't change the existence of the APIs in a running page.  The flag exists to force enable the API for cases like this.  Sorry for the trouble.
