### ISSUE TITLE
Current MS Pointer Events

### ISSUE THREAD

**Issue by rbiggs** [jquery/PEP#246]
I noticed that you seem to only be checking for Microsoft's vender prefixed versions of pointer events. For some time, since Windows 8.1 and IE 11, Microsoft dropped the prefix off of their pointer events and lowercased the names:
- pointerdown
- pointerenter
- pointerleave
- pointermove
- pointerout
- pointerover
- pointerup

**Comment by scottgonzalez** [comment]
Correct. Which means there's nothing for us to do, because the events already exist.
