### ISSUE TITLE
Test and see if webkit nightly support for touch-action works correctly

### ISSUE THREAD

**Issue by jacobrossi** [jquery/PEP#250]
Webkit added partial [`touch-action`](https://bugs.webkit.org/show_bug.cgi?id=149854) support.  It looks like, unfortunately, they only have `auto` and `manipulation` values.  But since the property is parsed now, this means the full cascade should work as expect. The only catch is -- can we retrieve a `none` value and use that for the events polyfill correctly if Webkit doesn't parse that value?

Regardless, I'm going to push the Apple folks to implement `none` for better interop.

**Comment by arschmitz** [comment]
@jacobrossi no it will throw the values away that are not supported so it does not help with out support of touch-action will still need to observe the prop and go the route we talked about previously

**Comment by jacobrossi** [comment]
Yeah, I posted this because of that: https://bugs.webkit.org/show_bug.cgi?id=133112

We'll see what happens!
