### ISSUE TITLE
PEP events firing twice on "-webkit-user-select:none;" elements on ios safari

### ISSUE THREAD

**Issue by beckiechoi** [jquery/PEP#251]
Hi,

It seems that PEP events are firing for both the touch and mouse events when the element has a css rule `-webkit-user-select:none` (on ios safari). I'm not entirely sure if this is an expected behavior or a bug, but the PEP events seem to work fine (by firing only once on touch events) when the css rule is not applied.

**Comment by bethge** [comment]
There should be only one pointer event for a touch event on iOS Safari. Safari's fallback mouse event should be suppressed by PEP.

Does this describe your situation: http://jsbin.com/kumapub/edit?console,output ?

With Safari running on iOS 9.2, I only get a single event per `pointerdown` event, with `pointerType: touch`.

**Comment by bethge** [comment]
Without further feedback, I will go ahead and close this issue.
