### ISSUE TITLE
delete is a reserved work in ie8

### ISSUE THREAD

**Issue by danieluhl** [jquery/PEP#253]
ie8 throws the error "Object doesn't support property or method" when calling delete on the SparseArrayMap object. Need to update the definition to 'delete': and all references from dot notation .delete to bracket notation ['delete']

**Comment by jdalton** [comment]
Let's drop IE8 support, if it is intended.

**Comment by scottgonzalez** [comment]
Indeed, we don't support IE8. See https://github.com/jquery/PEP#browser-compatibility.
