### ISSUE TITLE
Handle capture release when pointer is over a different element

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#254]
See notes from #177.

**Comment by scottgonzalez** [comment]
Depends on https://github.com/w3c/pointerevents/issues/15

**Comment by scottgonzalez** [comment]
This was discussed again in today's PEWG meeting. There was no decision made, but we're getting closer. There was a long discussion about a lot of event firing related to this and we may be changing the spec so that boundary events are completely removed during capture.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
