### ISSUE TITLE
pointerenter & pointerleave will not emit event on nested container

### ISSUE THREAD

**Issue by nissoh** [jquery/PEP#270]
This is fairly trivial case.

Having 2 elements, a container and a child. given the container inherit it's child dimensions it will no longer emit either pointerleave or pointerenter. adding margin to the child will emit what i've expected.

Here's a bin with the issue.
http://esnextb.in/?gist=dd6d0207f6fc726e7275

**Comment by dmethvin** [comment]
This sounds like a duplicate of #197, would you agree?

**Comment by nissoh** [comment]
@dmethvin yes, it looks like it is.
