### ISSUE TITLE
Adapt button property of touch-based pointer events

### ISSUE THREAD

**Issue by bethge** [jquery/PEP#273]
The `button` property of pointer events triggered by touch events needs to be adapted to the updated Pointer Events Specification (https://w3c.github.io/pointerevents/#h-the-button-property), as mentioned in https://github.com/jquery/PEP/pull/267#issuecomment-185793603.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
