### ISSUE TITLE
Is it possible to cancel the default behavior of an anchor element with the pointerdown or pointerup event?

### ISSUE THREAD

**Issue by dschissler** [jquery/PEP#276]
I have an anchor element with an href set and I want to cancel the default behavior but to still allow for some behavior when the link is opened in a new tab or window.

My old click handler looks like this:

```javascript
function(e) {
    console.log('click')
    e.preventDefault()
}
```

The `pointerdown` and `pointerup` events don't seem to be able to cancel the default behavior.

**Comment by scottgonzalez** [comment]
I assume when you say "my old click handler" you actually mean a handler for the `click` event. Why are you trying to change that?

**Comment by dschissler** [comment]
I need to be able to pan and to do other complex things.

**Comment by patrickhlauke** [comment]
`click` is not considered a "compatibility mouse event" and cannot be suppressed by issuing cancelling a pointer event. see the second note in https://w3c.github.io/pointerevents/#compatibility-mapping-with-mouse-events

> The click event, defined in [DOM-LEVEL-3-EVENTS], and the contextmenu event, defined in [HTML5], are not considered compatibility mouse events [...]
> In user agents that support firing click and/or contextmenu, calling preventDefault during a pointer event typically does not have an effect on whether click and/or contextmenu are fired or not.

**Comment by dschissler** [comment]
Thanks @patrickhlauke.

**Comment by dschissler** [comment]
So I simply use the 'click' event to cancel the event and then the JSy stuff is handled in the pointerup event.  So click is only used to disable the behavior.

**Comment by scottgonzalez** [comment]
Yes, this is really no different than mouse events (and that's the point). This is why I asked earlier why you were changing your `click` event handler.
