### ISSUE TITLE
Iframe does not fire events on touch-based drag-through

### ISSUE THREAD

**Issue by bethge** [jquery/PEP#277]
When starting and ending a touch-based drag outside an iframe, yet covering the iframe during the drag, the elements inside the iframe do not fire any events.

When doing this drag with a mouse, the elements in the iframe do fire `pointerenter` and `pointerleave` events.

See this little demo for visualization: http://bethge.github.io/pep-iframe/index.html

I would think `pointerenter` and `pointerleave` events should fire on elements in the iframe during a touch-based drag, though I could not find an explicit mentioning of iframes in the [specification](https://www.w3.org/TR/pointerevents/).

With the limited information exchange across iframes, this may be rather hard to fix.

**Comment by arschmitz** [comment]
@bethge you said specifically touch event based? there is an old iOS bug i don't think has ever been fixed about touch events and iframes ill get a reference for the bug if thats the case.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
