### ISSUE TITLE
properties return undefined

### ISSUE THREAD

**Issue by Bortxx** [jquery/PEP#285]
http://jsbin.com/kemuwanaqo/1

Why do pointerID and pointerType return undefined? Seems to work with "document.addEventListener" but not with jquery

**Comment by patrickhlauke** [comment]
This is not specific to PEP, but rather it's a quirk/feature of jQuery (for what it's worth, your jsbin also returns undefined in a browser that runs native pointer events, like MS Edge). Specifically, this is to do with the jQuery Event Object https://api.jquery.com/category/events/event-object/ which only includes and normalizes specific properties. `pointerId`, `pointerType` and all the other props that are new to Pointer Events are "other properties", so you need to use `event.originalEvent` - so in your jsbin

```
$("#test").on("pointerdown", function (e) {
                alert('pointerID: ' + e.originalEvent.pointerId);
                alert('pointerType: ' + e.originalEvent.pointerType);
            });
```

**Comment by patrickhlauke** [comment]
ah, and i see this is already explained here too https://github.com/jquery/PEP#using-pep-with-jquery
