### ISSUE TITLE
Pointer down only fire once when right click press on safari

### ISSUE THREAD

**Issue by padewitte** [jquery/PEP#286]
Hi,

I just spot that when a right click is perform on an element with Safari, i just get the pointerdown event one time. If i switch back to 0.3.0 i works well.

Here is a JSBIN http://jsbin.com/catexi/edit to quickly reproduce the issue (click pointer down)

Thank you for your help. This touch polyfill help us so much.

**Comment by patrickhlauke** [comment]
what do you mean "just get the pointerdown event one time"? how many pointerdown events are you expecting for a right-click?

**Comment by padewitte** [comment]
Hi,
I only get it the first time i right-click. After this first right-click no more touchdown event get fired event if i right or left click on my element.

I just solve my problem by handling  contextmenu event and disable it like that :

element.addEventListener("contextmenu", function(e){
            console.log("contextmenu");
            e.preventDefault();
            e.stopPropagation();
            return false; }
        );

**Comment by patrickhlauke** [comment]
Ah, i see, thanks for clarifying. Yes my guess would be that the context menu appearing is somehow throwing PEP off its game of keeping track of pointers - will have to investigate what happens in native PE implementations in these cases.
