### ISSUE TITLE
scroller not scrolling

### ISSUE THREAD

**Issue by Bortxx** [jquery/PEP#287]
I have several divs acting as buttons in a scrolling div. When I bind these buttons to an onclick event the scroller works when I swipe over any of the buttons. However when I switch to using PEP and bind the buttons to the pointer events (pointerdown, pointerup) to simulate a tap, the scroller no longer scrolls when swiping on the buttons. Does this have anything to do with setting touch-action="none" on the div buttons?

Also is there a gesture library that someone has built on top of PEP? I am finding myself having to build my own gesture API for simple things like Tap, Tap Hold, etc. Seems like something like this is basic enough that it should exist.

**Comment by scottgonzalez** [comment]
Gestures are outside the scope of PEP because they're outside the scope of Pointer Events.

For click, you should be using click, not generating your own gestures like tap.

**Comment by Bortxx** [comment]
Click is slow when repeated clicks in fast succession are needed and also does not support multiple simultaneous taps that's why its not suited for my application. Your saying it is not possible to have any elements use PEP that reside in a scrolling div without breaking the default scroll behavior?

I know gestures are outside the scope of PEP, that's why I asked if you knew of another library that uses PEP as a base to build gestures on top of it. Or are you saying it makes no sense to do this.

**Comment by scottgonzalez** [comment]
> Click is slow when repeated clicks in fast succession are needed and also does not support multiple simultaneous taps that's why its not suited for my application.

The description you provided of the working behavior didn't mention any of this. It'd be very helpful if you provided a reduced test case with an explanation of the desired behavior. From your original description, it sounded like all you wanted was standard click functionality inside a scrolling area.

> Your saying it is not possible to have any elements use PEP that reside in a scrolling div without breaking the default scroll behavior?

No, I never said that. Setting `touch-action="none"` means "Touches that begin on the element must not trigger default touch behaviors." So if the default behavior is to scroll, you're telling the browser not to scroll.

> I know gestures are outside the scope of PEP, that's why I asked if you knew of another library that uses PEP as a base to build gestures on top of it. Or are you saying it makes no sense to do this.

I'm not sure if there are gesture libraries built on Pointer Events yet. Polymer took that approach at one point, but switched to using mouse and touch directly. I'm not sure where that stands today as I've not been following gestures. It's worth noting that you wouldn't be looking for a gesture library built on PEP, you'd be looking for a gesture library built on Pointer Events (the code shouldn't know there's a difference).

**Comment by Bortxx** [comment]
So basically I have a scrolling pane with row like div buttons on it. So there is very little of the scrolling panel directly touchable. The user should be allowed to tap on any of the buttons but if swiping up and down the scroller should be engaged. Why am I not using onclick and using PEP? Because I want to allow the user to click on multiple buttons simultaneously. onclick doesn't support this. So basically when the user swipes up/down on the button I need the scroller panel the button is contained in to scroll except when the user taps on the button where I would engage the button's function.

**Comment by scottgonzalez** [comment]
Can you please provide a reduced test case that we can work from?

**Comment by patrickhlauke** [comment]
without a reduced test case for the last 9 months, i'd suggest closing this issue?
