### ISSUE TITLE
attribute touch-action="none"

### ISSUE THREAD

**Issue by Bortxx** [jquery/PEP#289]
Can I get a better explanation on how the attribute touch-action="none" works? I understand it is needed for on the event bound element to work but I noticed that it is needed only needed the first time the page script runs. I removed this attribute and the code still works as long as I had it there at least once. Are you caching this in client storage or something. 

Does the attribute have to be added inline or can it be added like this:
`
$.fn.tap = function (callBack) {
    var pointers = {};

    $(this)
        .attr('touch-action', 'none')
        .on('pointerdown', function (e) {                    
            pointers[e.originalEvent.pointerId] = {
                downX: e.clientX,
                downY: e.clientY
            };
        })
        .on('pointerup', function (e) {
            var pointer = pointers[e.originalEvent.pointerId];
            if (!pointer) return;
            var dist = Math.sqrt(Math.pow(e.clientX - pointer.downX, 2) + Math.pow(e.clientY - pointer.downY, 2));
            if (dist <= 10) {
                callBack.call(this);
                delete pointers[e.originalEvent.pointerId];
            }
        });
};`

**Comment by scottgonzalez** [comment]
We watch for changes to the attribute. This is working properly for me. Can you please provide a reduced test case showing that the behavior is not working as expected for you?

Note that this only applies to touch, not mouse.

**Comment by arschmitz** [comment]
@borxx what platform are you on we use mutation observers which are not supported in older android browsers

**Comment by Bortxx** [comment]
For example in the code below I am extending jquery with this gesture function I will be using a lot. Since I need the pointermove and pointerup to be raised even when the finger goes off the pointerdown target as long as it is initiated there, I bound those events to the document. However when I add the "touch-action" attribute to the document that breaks other native touch behavior that I need so I removed it which makes it work. However the attribute can not be removed from the pointerdown element. So I am confused when it is needed and when not aside from trial and error.

`$.fn.pointerDrag = function (callBack) {
    var pointers= {};    

    $(this)
        .attr('touch-action', 'none')   // needed for PEP API
        .on('pointerdown', function (e) {
            pointers[e.originalEvent.pointerId] = {
                downX: e.clientX,
                downY: e.clientY,
                elem: this
            };
            callBack.call(this, {
                action: 'down',
                delta: {
                    x: 0,
                    y: 0
                }
            });
        });
    
    $(document.body)        
        //.attr('touch-action', 'none')   // works without it and breaks native behavior with it
        .on('pointermove', function (e) {
            var pointer = pointers[e.originalEvent.pointerId];
            if (!pointer) return;
            callBack.call(pointer.elem, {
                action: 'move',
                delta: { 
                    x: e.clientX - pointer.downX, 
                    y: e.clientY - pointer.downY 
                }                
            });
        })
        .on('pointerup', function (e) {
            var pointer = pointers[e.originalEvent.pointerId];
            if (!pointer) return;
            callBack.call(pointer.elem, {
                action: 'up',
                delta: {
                    x: e.clientX - pointer.downX,
                    y: e.clientY - pointer.downY
                }
            });
            delete pointers[e.originalEvent.pointerId];
        });
};`

**Comment by scottgonzalez** [comment]
What you really want is `setPointerCapture()`. This is one of the huge benefits of Pointer Events, you can force the events to be retargeted to the element you care about and not have to worry about binding your events higher up just to capture the movements. Read through https://www.w3.org/TR/pointerevents/#pointer-capture and if you still have questions, just post another comment.

**Comment by Bortxx** [comment]
I understand somewhat but don't get how to implement the above to use setPointerCapture() instead. So instead of binding 'pointermove' and 'pointerup' to the 'body' like above, what do I bind them to?

What I am trying to achieve is to capture 'pointerdown' on a given element but  'pointermove' and 'pointerup', for that given element, on any element in the body. Also if user's pointer drifts off the screen to capture 'pointerup' so I can do cleanup. Is this possible? How?

**Comment by scottgonzalez** [comment]
Great, it sounds like this issue has been resolved. Can you confirm that this can be closed now?

**Comment by Bortxx** [comment]
Yes, it can be closed.
