### ISSUE TITLE
"use strict" breaks PEP on IE11.

### ISSUE THREAD

**Issue by leofavre** [jquery/PEP#291]
PEP 0.4.1 is not working on IE11 (Win7 running on Oracle Virtual Box). The error says: "Assignment to read-only properties is not allowed in strict mode".

![screenshot](https://cloud.githubusercontent.com/assets/125764/15684747/d53498f6-273e-11e6-8a41-2b517a05b541.png)

**Comment by arschmitz** [comment]
This is an issue with the demo not PEP. PEP is a noop on ie11 since it has native pointer events and PEP is a polyfill. However i just tried this demo on IE11 and cannot reproduce this error. What exactly are you doing to cause this error to happen?

**Comment by leofavre** [comment]
The problem happens to all the demos, not only this one. You simply move the cursor around the screen to trigger the error.

But this may be related, somehow, to the virtual machine that i use to test browsers on IE. Using another another combination of VM and Windows version, but still keeping IE11, the problem does not oocour.

**Comment by patrickhlauke** [comment]
unless i'm misremembering, IE11 on different versions of Windows will be subtly different, as it uses at least part of code that's integral to the OS itself. so yes it's likely that on older Windows versions some stuff may break.

**Comment by patrickhlauke** [comment]
FWIW using the most recent IE11/Win7 image from modern.ie, I can't replicate the error - suggest this is only a problem (of the demo?) in older versions of IE11 that are not up-to-date (well, as up-to-date as one can get when still running Win7), so can probably be closed?

![ie11win7](https://cloud.githubusercontent.com/assets/895831/15704127/17dc5692-27e1-11e6-94b3-cd2f25d303e5.PNG)

**Comment by thenickdude** [comment]
I get this error with 0.4.3 when using IE10, or IE11 in IE10 emulation mode, both on Windows 7. No errors with IE11 in IE11 mode. It's triggered on the assignment to "relatedTarget" in makeEvent.
