### ISSUE TITLE
Samples not working - cannot find pep.js

### ISSUE THREAD

**Issue by DARKSETH23** [jquery/PEP#293]
Hi guys, just downloaded this library.
None of the samples work for me:

error: failed to load resource::ERR_FILE_NOT_FOUND file://.../PEP-master/dist/pep.js

I'm looking through the repository here and there is no "/dist" directory or "pep.js" file.
Am I blind or is there something else I need to do?

**Comment by arschmitz** [comment]
You need to build the library first. to do this you need to run `npm install` then `grunt`

**Comment by patrickhlauke** [comment]
I take it you didn't actually run grunt?

**Comment by DARKSETH23** [comment]
Ah!
apologies for my ignorance, I missed that instruction.

I have run npm install resulting in getting the node_modules directory.
I can't seem to run grunt. no matter what directory I'm in.
Is there some other method I'm supposed to be using?

again, sorry. Assume I know nothing :)

**Comment by arschmitz** [comment]
@DARKSETH23 you also need to install the grunt cli if you have not previously on your system `npm install grunt-cli -g`

**Comment by DARKSETH23** [comment]
Ok awesome!
Got everything I need... don't know what all that was about but it's working.
Thank you very much for your help and patience.

I will read up on what all of this is, thank you again :+1: @arschmitz

**Comment by arschmitz** [comment]
@DARKSETH23 no problem looks like we have not actually documented this process so i opened an issue for this
