### ISSUE TITLE
Document how to build pep

### ISSUE THREAD

**Issue by arschmitz** [jquery/PEP#294]
We need to document, most likely in the readme, how to build pep from the repo and use the examples. 

basicly just
1. install `node` if you have not already link to node binarys
2. install `grunt cli` if you have not already `npm install grunt-cli -g`
3. `npm install`
4. `grunt`

ref gh-293

**Comment by jzaefferer** [comment]
Could skip one step by adding grunt-cli to package.json and adding another entry in `scripts`, then the last step would be `npm run build` or something like that.
