### ISSUE TITLE
Pointermove not firing on chrome touch (phone and touch emulater)

### ISSUE THREAD

**Issue by niek1414** [jquery/PEP#302]
Hello,
I don't know if this repository is still active or the plugin maintained,
but i can't seem to get the pointermove event to fire on chrome touchdevices (and emulater).
Here is a fiddle: http://jsfiddle.net/bamk14sm/

From time to time it does fire before pointerup does.
When it dit work it worked great on all devices, thanks for this amazing piece of code.
Hope you get it working again (or i am missing something and is my fault :) ).

**Comment by bethge** [comment]
Hi @niek1414,

for PEP to work you will have to add the HTML attribute `touch-action` to the div element. See: https://github.com/jquery/PEP#touch-action and the examples in the _Getting Started_ section.

Let me know if that resolves your issue.

**Comment by niek1414** [comment]
A, sorry i put it in the CSS sorry. 
However the result is the same for me..
Here is the new fiddle:
http://jsfiddle.net/992rjcdv/

**Comment by bethge** [comment]
I am on OS X with Chrome 51. When I open your latest fiddle, open the Chrome Dev Tools and activate iPhone 6 simulation. I can drag around in the rectangle and the timestamps go up.

Some months ago when I was debugging `mousemove` and `pointermove` events, they suddenly wouldn't fire anymore when I have the Chrome Dev Tools open. I had to close all browser tabs and all Chrome Dev Tools tabs and restart Chrome for the events to come back.

If that doesn't do the trick either, we'll need more information on your setup.

**Comment by niek1414** [comment]
Uhm, i am on Versie 51 too (51.0.2704.103) 
And my OS is Windows 10.
I had the problem already yesterday (but before it worked normaly).
The pc rebooted last night and to be sure i just restarted the browser.

**Comment by patrickhlauke** [comment]
> http://jsfiddle.net/992rjcdv/

just to confirm it wfm in Chrome 51 / Android 6, as well as Chrome 51 / Windows 10 with DevTools open

**Comment by niek1414** [comment]
Well, if i know it's only in my DevTools then its not a problem.
I will try my laptop later, but i am sure it i'll work. 
I will reinstall chome later to see if that fixed it.
Thanks for the qwick response! (and a plugin that is easy to use)

**Comment by bethge** [comment]
Ok. I'll close this for now and if others report the same issue, we'll reopen and investigate further.
