### ISSUE TITLE
Use `InputDeviceCapabilities.firesTouchEvents` to detect mouse events from touch events

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#307]
[`InputDeviceCapabilities.firesTouchEvents`](http://wicg.github.io/InputDeviceCapabilities/#dom-inputdevicecapabilities-firestouchevents) might be the best way for us to detect that a mouse event was caused by a touch event and should therefore be ignored.

See also [the MDN page](https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceCapabilities/fireTouchEvents).

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
