### ISSUE TITLE
Confusing use of "touch-action" and mention in README

### ISSUE THREAD

**Issue by computersarecool** [jquery/PEP#310]
The README says:
>Due to the difficult nature of polyfilling new CSS properties, this library will use a touch-action attribute instead

Unless I am mistaken, this is an invalid custom attribute that needs to be added to HTML (Thus invalidating the HTML).

Shouldn't this be mentioned in the README as right now it sounds like this is an official attribute.  Additionally, is there a reason not to use the data-* attribute (as I thought that is exactly it's purpose).

**Comment by scottgonzalez** [comment]
Yes, it's technically invalid. But it will never be standardized and the use of the attribute will eventually go away. This was already in place before we took ownership of the project and changing it now has very little benefit while it has the downside of requiring every user to update their markup.

You can follow #151 for the removal of the attribute.
