### ISSUE TITLE
Fully polyfill touch-action behaviour for scrolling

### ISSUE THREAD

**Issue by bethge** [jquery/PEP#311]
While looking into (#309) using passive event listeners and the native `touch-action` property, we came across some inconsistencies in PEPs way of calculating the `touch-action` property.

The [spec](http://www.w3.org/TR/pointerevents/#the-touch-action-css-property) says:

> When a user touches an element, the effect of that touch is determined by the value of the touch-action property and the default touch behaviors on the element and its ancestors. To determine the effect of a touch, find the nearest ancestor (starting from the element itself) that has a default touch behavior. Then examine the touch-action property of each element between the hit tested element and the element with the default touch behavior (including both the hit tested element and the element with the default touch behavior). If the touch-action property of any of those elements disallows the default touch behavior, do nothing. Otherwise allow the element to start considering the touch for the purposes of executing a default touch behavior.

Up to now, we have not properly calculated the intersection of the `touch-action` properties of all ancestors of an element up to _the element with the default touch behaviour_.

To us, the default _scroll_ behaviour is the most relevant default touch behaviour and generally the one with the most impact.

For scrolling, the element "creating" a scrollable area is the one with the default scroll behaviour. E.g. an element with the CSS property `overflow: scroll` will be the the element with default scroll behaviour, its children will not be.

An element has a default scroll behaviour if (not guaranteed to be all cases):
- It has the CSS property `overflow: scroll`, `overflow-x: scroll` or `overflow-y: scroll`
- It has the CSS property `overflow: auto`, `overflow-x: auto` or `overflow-y: auto` and the content is larger than the element.

[An example](http://bethge.github.io/touch-action/pep-touch-action.html) of the different behaviours. Try it in Chrome with the mobile emulator. 

[Chrome's implementation](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/input/TouchActionUtil.cpp?sq=package:chromium&dr=CSs&rcl=1473391583&l=21) for computing the `touch-action` value.

This mostly just summarises this weeks PEP meeting. Thanks to @rbyers for the insights!

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
