### ISSUE TITLE
pointer event is fired on disabled element

### ISSUE THREAD

**Issue by zerbino** [jquery/PEP#312]
Hello,

When putting touch-action="none" on a disabled element, pointer events might be fired when touching the element. I know that setting touch-action to "none" disables default behavior such as scrolling and panning, but I didn't expect it to bypass the disabled tag. 

Is this expected behavior? I observed this on iOS 9.2.

**Comment by patrickhlauke** [comment]
testing on Edge with native Pointer Events, no...a `disabled` control (like a `button`) should not fire any pointer events (horribly hacky test https://jsfiddle.net/9rs98mv6/6/)

**Comment by NekR** [comment]
Why disabled element should prevent any events than click? If Edge has that behavior, it doesn't that's true.

IE and Firefox inherently have a bug which prevents all the events on disabled elements (and/or elements under disabled fieldset), while HTML spec says that only click event should be prevented (at least it was that couple of years ago when I read, did it change?).

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
