### ISSUE TITLE
w3c tests out-of-date and failing

### ISSUE THREAD

**Issue by appsforartists** [jquery/PEP#314]
`tests/w3c` seems to be populated by the SHA referenced in `package.json['web-platform-tests'].repo`.  It's currently pointing at a really old SHA (from 2015).  When I try to update it, I receive this error:

```
Running "pretest" task
Unhandled rejection Error: EISDIR: illegal operation on a directory, open '~/Projects/PEP/tests/w3c/resources'
    at Error (native)
```

If I kill the process and run it again, it goes further, but most of the tests fail:

```
NoSuchElement: [POST http://localhost:4444/wd/hub/session/f93260d5-52de-439a-bf86-bca9471abfa0/element / {"using":"id","value":"target0"}] no such element: Unable to locate element: {"method":"id","selector":"target0"}

or

ScriptTimeout: [POST http://localhost:4444/wd/hub/session/f93260d5-52de-439a-bf86-bca9471abfa0/execute_async / {"script":"return (function (poller, args, timeout, pollInterval, done) {\n\t\t\t\t\t\t/* jshint evil:true */\n\t\t\t\t\t\tpoller = new Function(poller);\n\n\t\t\t\t\t\tvar endTime = Number(new Date()) + timeout;\n\n\t\t\t\t\t\t(function poll() {\n\t\t\t\t\t\t\tvar result = poller.apply(this, args);\n\n\t\t\t\t\t\t\t/*jshint evil:true */\n\t\t\t\t\t\t\tif (result != null) {\n\t\t\t\t\t\t\t\tdone(result);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\telse if (Number(new Date()) < endTime) {\n\t\t\t\t\t\t\t\tsetTimeout(poll, pollInterval);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\telse {\n\t\t\t\t\t\t\t\tdone(null);\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t})();\n\t\t\t\t\t}).apply(this, arguments);","args":["return (function () {\n\t\t\t\t\treturn window.w3cTests;\n\t\t\t\t}).apply(this, arguments);",[],1000,67]}] asynchronous script timeout: result was not received in 1 seconds
```

My current strategy is to look at the git history (back 20 pages, back 10 pages, etc.) to figure out which commit broke the PEP tests.  It's effectively git bisect, but across repos.

**Comment by appsforartists** [comment]
The 1st problematic commit is https://github.com/material-foundation/web-platform-tests/commit/c5d333c859075744b3828a2a29057ee456234cb2

**Comment by appsforartists** [comment]
`npm run test` isn't copying the HTML files in `resources` correctly:

<img width="1920" alt="screen shot 2016-09-21 at 4 43 20 pm" src="https://cloud.githubusercontent.com/assets/926648/18732827/fd5532b6-801a-11e6-9d41-0e4b2e64aa0e.png">

However, adding those files in manually doesn't fix the `NoSuchElement` error.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
