### ISSUE TITLE
Document testing process

### ISSUE THREAD

**Issue by appsforartists** [jquery/PEP#315]
At the very least, this should be in `CONTRIBUTING.md`:
- Change `package.json` to point at the relevant [web-platform-tests](https://github.com/w3c/web-platform-tests/) commit.
- `npm run test`
- If `./tests/w3c/.sha` doesn't match what's in `package.json`, `npm run test` will download the commit in `package.json` from GitHub and clobber `./tests/w3c/`

Is there a way to point `npm run test` at a local clone of `web-platform-tests` without hacking on `pretest`?

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
