### ISSUE TITLE
IE Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by bencroskery** [jquery/PEP#320]
IE 9/10 get an `Object doesn't support property or method 'contains'` error on Line 463, [here's the source](https://github.com/jquery/PEP/blob/master/src/dispatcher.js#L316). An easy fix is to use the already implemented contains function, although I don't know what the appropriate fix is.

The error is reproducible on any of the [samples](http://jquery.github.io/PEP/).

**Comment by bethge** [comment]
Thank you for the bug report! I believe IE 9 is not supported by PEP, but IE 10 certainly is.

It seems like we have run into [this IE bug][1]: Only nodes of type `Element` support `.contains()`. 
[1]: https://connect.microsoft.com/IE/feedback/details/780874/node-contains-is-incorrect

Iiuc, on the last iteration of the event propagating up the DOM, we run `!target.contains(event.relatedTarget)` with `target === document`. Yet `document` is not an instance of `Element`.

Rotating the two conditions of the `while` loop might already do the job for this case.

I am uncertain if there can be other non-`Element` nodes when traversing the DOM. Afaik `Text` nodes can only be leaves, so they would not be traversed when going up/down the DOM.
Yet can they still be the first target of a pointer event? They _are_ an instance of the `EventTarget` interface.

**Comment by slavapvf** [comment]
have this issue with svg image on a page. the image is svgimagedocument
