### ISSUE TITLE
throw error while remove target element in pointerup event

### ISSUE THREAD

**Issue by shjyh** [jquery/PEP#326]
pep.js throw 

> TypeError:Cannot read property 'contains' of null

and freeze scroll (ios) while remove target Element from dom tree in pointerup event handler.

it seems trigger 'pointerleave' event after I removed target Element from dom tree, but pep try to find ancestor elements until document. (pep.js:463)

**Comment by bethge** [comment]
Hi, thanks for reporting this bug!

I went ahead and did a small demo with a `pointerdown` which causes the same error: http://bethge.github.io/PEP/gh-326/index.html

iOS Safari is rather asynchronous when it comes to event callbacks and, from what I can tell, this causes the element to be removed from the DOM before PEP starts processing the event. Causing the parent node of the element to be `null`.

To fix this, the easy response would be to check for `null`. Aiming for more correctness we should  check how `pointerleave`, `pointerenter` and subsequent events should actually propagate.

On a first glance, I did not find a mention about the intended behaviour in the PE spec. 

The [DOM Level 3 Events Spec][1] specifies for mouse events:

> If the event target (e.g. the target element) is removed from the DOM during the mouse events sequence, the remaining events of the sequence MUST NOT be fired on that element.

> If the target element is removed from the DOM as the result of a mousedown event, no events for that element will be dispatched for mouseup, click, or dblclick, nor any default activation events. However, the mouseup event will still be dispatched on the element that is exposed to the mouse after the removal of the initial target element. Similarly, if the target element is removed from the DOM during the dispatch of a mouseup event, the click and subsequent events will not be dispatched.

We should also check the behaviour of Chrome and IE/Edge in this case.

[1]: https://www.w3.org/TR/DOM-Level-3-Events/#example-2cc85912

**Comment by studio-marweb** [comment]
Hello @bethge, have you any updates regarding this issue?

**Comment by peteruithoven** [comment]
We're noticing the same error on iOS. The error seems to come from the [propagate function in the dispatcher](https://github.com/jquery/PEP/blob/master/src/dispatcher.js#L318).

**Comment by bethge** [comment]
Apologies for the delay. Let me wrap my head around it again and get back to you.

**Comment by madmed88** [comment]
will this get released soon?

**Comment by scottgonzalez** [comment]
yes
