### ISSUE TITLE
Incorrect pointerType in desktop FF for touch events

### ISSUE THREAD

**Issue by dwelle** [jquery/PEP#327]
`pointerenter`/`pointerdown` events (haven't tested others) have `pointerType` set to `mouse` when the event is initiated via touch.

As a sidenote, it's also set to `mouse` when the pen (stylus) is used.

Tested on desktop Firefox `55.1.0`, on a Surface Book 4 Windows 10 touchscreen, pep `0.4.1`

**Comment by bethge** [comment]
Could you check what kind of events (`mouse` or `touch`) are fired when you use the touchscreen? (Very plain but should do the job: http://jsbin.com/nuvuki/edit?js,console,output).

It might be that Windows 10 sends touches to FF, which turns them into mouse events. We can only take the events the browser fires and turn them into pointer events.

**Comment by roblarsen** [comment]
American football fan?

``` javascript
document.addEventListener('touchdown', function(e) {
  console.log(e.type);
});
```

With `touchstart` the behavior is as you suspected. Chrome returns the real event and then the compatibility event ("touchstart" "mousedown".) Firefox returns just "mousedown"

**Comment by bethge** [comment]
Haha, thank you for catching that!

To me, it appears like a limitation of Firefox on Windows. It would be great if Firefox would generate touch events when using Surface's touchscreen. It would allow PEP to give the proper `pointerType`.

I am afraid there is nothing we can do to solve the problem. I would close this issue, if there are no objections.
