### ISSUE TITLE
pointerdown not fired when added inside <object>

### ISSUE THREAD

**Issue by julmot** [jquery/PEP#328]
I'm embedding a SVG via `<object>` and adding a pointerdown event on the root `<svg>` element. This event will never be fired with `pointerdown` and PEP, but `click` works.

**Comment by patrickhlauke** [comment]
I'd guess that you need to include PEP as a script inside the actual SVG as well, since with `<object>` you've created a whole separate little world that's separate from your host page. If you included the <svg> directly insider the HTML, I would think that it will work, conversely.

**Comment by julmot** [comment]
@patrickhlauke I guess so too, but since elements embedded via `<object>` or even `<iframe>` can be external (no write permissions) and since the event was added via the parent (root) document, I expect that everything necessary is done by PEP.

**Comment by patrickhlauke** [comment]
if they're external, then it's up to whoever owns them to add relevant polyfills if they're using features like PE that aren't yet in all browsers, no?

**Comment by patrickhlauke** [comment]
as otherwise you're expecting PEP to go through the current (root) document, find any instances of iframes, objects, etc, and then try to inject PEP code into them (which would likely not work for security reasons)...

**Comment by julmot** [comment]
> which would likely not work for security reasons

Adding events to elements which whom I don't have access to wouldn't work either. I didn't dig into the code and inspected how PEP works, but maybe there's an alternative instead of adding the `<script>`? The event is added in the root scope, so maybe there's a way to proxy something?

**Comment by patrickhlauke** [comment]
> Adding events to elements which whom I don't have access to wouldn't work either

But why are those elements listening for pointer events without providing their own polyfill for browsers that don't support them? I'm failing to understand your use case...fixing something like an SVG that just relies on native PEs and making it work in non-PE browsers?

**Comment by patrickhlauke** [comment]
So in the case of your thread starter

> I'm embedding a SVG via `<object>` and adding a `pointerdown` event on the root `<svg>` element. 

In this situation I'm assuming *you* are in control of the SVG, so will be up to you to add polyfill to your SVG if that's what you want to rely on in the SVG.

**Comment by julmot** [comment]
Seems like we've misunderstood each other. 

> In this situation I'm assuming you are in control of the SVG

That's not the case. It's true that **I** am embedding the SVG and adding the event, but I'm adding it from the outer HTML page, not within the SVG element.

Example:

```javascript
const svg = document.getElementById("vector"),
    svgDoc = svg.contentDocument,
svgDoc.querySelector("svg").addEventListener("pointerdown", e => {
    console.log(e);
});
```

This won't work. But, as I'm adding the event from the outer HTML, not from within the SVG, I expect it to work since PEP is available in there.

I hope it's clear now.

**Comment by patrickhlauke** [comment]
ok so you're programmatically injecting the event listener. then currently you'll also need to inject a `<script>` to load PEP into the svg.

this scenario does feel a bit...edge-case-y to me, but leaving it up to PEP project leads to decide

**Comment by tuxmachine** [comment]
A possible workaround is loading the SVG using ajax and inserting it into current document. PEP will work fine then.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
