### ISSUE TITLE
Nested elements don't bubble correctly if the child has touch-action: auto

### ISSUE THREAD

**Issue by appsforartists** [jquery/PEP#336]
[Reduction](http://codepen.io/appsforartists/full/WpozRG)

Consider this DOM:

```
<div touch-action = "none">
  <span>
    some content that isn't in the auto box
  </span>
  <div touch-action = "auto">
    the auto box
  </div>
</div>
```

with a `pointermove` listener attached to the outer element.

In Chrome (with native PointerEvents), it receives events that begin in itself or its `touch-action: auto` child.

In Safari with PEP, it only receives events that begin outside the `touch-action: auto` child.

**Comment by bethge** [comment]
I believe this is pretty much the same issue as #311. I did title that one poorly (feel free to change it). PEP currently does not properly polyfill nested `touch-action` behaviour.

**Comment by scottgonzalez** [comment]
Closing as duplicate of #311.
