### ISSUE TITLE
ETA new release? 

### ISSUE THREAD

**Issue by peteruithoven** [jquery/PEP#337]
We noticed that since the 0.4.2 release there has been a [fix created](https://github.com/jquery/PEP/commit/0fae1e51895ca759432efbb93780003c4f60e593) for IE 10 which I think we're experiencing. Is there an ETA on a new release? 
https://github.com/jquery/PEP/compare/0.4.2...master

**Comment by scottgonzalez** [comment]
We're working on a few more updates and hope to release very soon.

**Comment by scottgonzalez** [comment]
We released v0.4.3 over the weekend.
