### ISSUE TITLE
iOS 10.3 only one pointermove in 0.4.2

### ISSUE THREAD

**Issue by DimitryDushkin** [jquery/PEP#340]
After upgrading 0.4.1 -> 0.4.2 continuous `pointermove` is broken. Now events on dragging looks like this `pointerdown - pointermove - pointerup`, but it should be `pointerdown - pointermove - pointermove - pointermove - ... - pointermove - pointerup`.

Code is here - https://gist.github.com/DimitryDushkin/a6425d4db9b42871b1b1aa8ee8e8ec44 
I'm using `setPointerCapture` in `pointerdown`.

**Comment by patrickhlauke** [comment]
are you also setting a relevant `touch-action`? wondering if that's potential source of the problem...

**Comment by DimitryDushkin** [comment]
I found the problem is in `this.el.setPointerCapture(e.pointerId);`, if this line is removed while using 0.4.2 everything works.

**Comment by scottgonzalez** [comment]
Setting pointer capture changes how the events are targeted. Without a reduced test case to look at, we can't really tell what behavior you're seeing and whether or not it's correct.

**Comment by DimitryDushkin** [comment]
Sorry, I'll try to provide jsbin example. I thought it might be known issue.

**Comment by DimitryDushkin** [comment]
Cannot reproduce on [clean example](http://jsbin.com/feyute/edit?html,css,js,output). Working on it. Issue can be closed I think.

Thank you for great polyfill!
