### ISSUE TITLE
pointermove events cancelled after initial on touch devices

### ISSUE THREAD

**Issue by pablosbrain** [jquery/PEP#346]
Using Chrome and MS Edge I have found an issue that pointer move events stop getting fired after the first one when touching and dragging. Simple example:
```
var pointerE = function(pointerEventObj){
  console.log(pointerEventObj.type, pointerEventObj.pointerType, pointerEventObj.pointerId);
}
document.addEventListener("pointermove", pointerE, false);
document.addEventListener("pointerdown", pointerE, false);
document.addEventListener("pointerup", pointerE, false);
document.addEventListener("pointerover", pointerE, false);
document.addEventListener("pointerout", pointerE, false);
document.addEventListener("pointerenter", pointerE, false);
document.addEventListener("pointerleave", pointerE, false);
document.addEventListener("pointercancel", pointerE, false);
```
This example results in the following output:
```
pointerover touch 1
pointerenter touch 1
pointerdown touch 1
pointermove touch 1
pointercancel touch 1
pointerout touch 1
pointerleave touch 1
```
* User presses finger/touch down on document to initiate.
* While pressed, drags finger/touch across screen.
* pointermove, pointercancel, pointerout, pointerleave all fire cancelling any further move events.
* When user releases finger/touch the pointerup does not fire after dragging.
* pressing and releasing finger/touch without movement results in the appropriate events being fired.

**Comment by pablosbrain** [comment]
Events all work properly for mouse input.

**Comment by patrickhlauke** [comment]
assuming you set an appropriate `touch-action`?

**Comment by scottgonzalez** [comment]
Both of those browsers have native Pointer Events. You should not be hitting any code from PEP. Can you verify whether this behavior occurs when PEP is not included on the page?

**Comment by pablosbrain** [comment]
Yes. I have touch-action attribute set.
Good call @scottgonzalez. I removed PEP to test in those browsers and am still having issues. I'll comment back when I find the issue.

**Comment by patrickhlauke** [comment]
if it still happens without PEP, it's not a PEP issue, so probably no point commenting back here :)

the fact that `pointercancel` is fired indicates that the browser's default action is not being prevented and the pointer gesture is being cancelled. and note that in real pointer events (not PEP'd) `touch-action` is a CSS property, so make sure you set it in your CSS (as well as the `touch-action` attribute in your HTML to make PEP work correctly in browsers where pointer events are NOT supported and PEP kicks in).

**Comment by HjalmarSnoep** [comment]
For anyone asking themselves what  "an appropriate touch-action" would be. "none" would usually be appropriate. I just fixed a very similar bug that way. I came looking here for the answer and didn't find it.
"NONE" tells the browser to not interpret the events in anyway (or the official description: Disable browser handling of all panning and zooming gestures). 

For ease of use, you can also set this via Javascript: myCanvas.style.touchAction="none";
Using pep.js or not didn't make any difference, but this fixed my problem, so I thought, I'd help by answering the initial question.

**Comment by Athinodoros** [comment]
@HjalmarSnoep Thanks for coming back to answer I was looking for that all over the web 👍 💯 😃
