### ISSUE TITLE
touch-action: none requirement - not available for Safari/iOS

### ISSUE THREAD

**Issue by lkgarrison** [jquery/PEP#350]
I'm trying to use PEP on Safari and Chrome/Safari on iOS, but it doesn't seem to be working on these browsers because I can't set `touch-action: none` since this CSS property isn't supported on these browsers [https://caniuse.com/#search=touch-action](https://caniuse.com/#search=touch-action)

Has anyone else encountered this issue? It seems to be working fine on Chrome and Android browsers.

**Comment by patrickhlauke** [comment]
for PEP you need to set touch action as a variable in HTML (on top of doing it in CSS for browsers that natively support Pointer Events). https://github.com/jquery/PEP#touch-action

**Comment by lkgarrison** [comment]
Ah, thank you! To clarify for anyone who comes across this in the future, you need to specify `touch-action: none` in two places: in the HTML (for browsers that do **not** support pointer-events and in the CSS (for browsers that **do** support pointer-events.


HTML:
`<canvas id="canvas" touch-action="none">
</canvas>`

CSS:
`#canvas {
    touch-action: none
}`

In my opinion, this could be clarified a bit more in the repository's README for new, unfamiliar users. Thank you so much for developing PEP!

**Comment by scottgonzalez** [comment]
It's already mentioned a few times in the README, but if you think it can be called out more clearly, please file a pull request with the changes.

**Comment by betovieirasilva** [comment]
Hey guys, 

below there is one example which has resolved for me:
`<md-content layout="column" id="content" flex class="md-padding" style="touch-action: manipulation !important;">`
