### ISSUE TITLE
pep.js and Mac and pointerup

### ISSUE THREAD

**Issue by instagramlover** [jquery/PEP#352]
$(document).on("pointerup", ".activityStatusButton", function() {
//...............
})

this never worked on  mac / safari

**Comment by patrickhlauke** [comment]
please provide a reduced test case (jsfiddle or similar) to show the problem

**Comment by aaronransley** [comment]
I am running into the same issue. No test case here, apologies, just a +1

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
