### ISSUE TITLE
Unable to bind to elements within shadow root on Safari...

### ISSUE THREAD

**Issue by gratbodkin** [jquery/PEP#353]
When attempting to bind to an element within a shadow root on Safari, PEP instead binds to the host element..

Tried looking at the examples (specifically, shadow.html).  That example does not run for 2 reasons:
1. webkit.createShadowRoot has been deprecated, and replaced with el.attachShadow

2. It appears the PEP API has changed as well, in that PointerEventsPolyfill.register(showdowRoot) no longer seems to exist.

As a result, I have a few questions:

In safari, if I need to bind to an element within a shadow root, am I required to somehow register the shadow host with PEP?

If so, how do I do it?

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
