### ISSUE TITLE
Unable to use pointer events under a shadow dom

### ISSUE THREAD

**Issue by F2X** [jquery/PEP#354]
I noticed some issues when trying to use pepjs under a web component:
I'm migrating from Polymer 1.9 to 2, which supports shadow dom, and PointerEvents are not forwarded to elements within the shadow root.

I think it's related with #353 and #305.

**Comment by Idicious** [comment]
I'm not sure how cross browser compatibility is with this but instead of event.target you can use event.path[0] in Polymer.

**Comment by IanBellomy** [comment]
Same issue but am working with vanilla WC, any tips?

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
