### ISSUE TITLE
Apple Pencil and Finger Simultaneous Input is Blocked

### ISSUE THREAD

**Issue by GautamBose** [jquery/PEP#359]
I am having an interesting issue when trying to use the Apple Pencil simultaneously with finger input. It is clear that the hardware supports it as many apps take advantage of it. However, when a finger is down all touch input form the pencil is blocked and vice versa. I don't think that this is any 'palm rejection' functionality either, as again, other apps do support it.

**Comment by patrickhlauke** [comment]
I don't have an iPad Pro/Pencil available to test, but wondering if in browsers the touch events for both fingers and pencil are exposed simultaneously or not (i.e. whether being able to use both is only something that can be achieved in native apps).

Can you test https://patrickhlauke.github.io/touch/tracker/multi-touch-tracker-pointer-hud.html and see if fingers and pencil are reported simultaneously or not?

**Comment by GautamBose** [comment]
Okay I just gave it a run and the same issue is occurring, I can't see both at the same time. I guess it is an issue with what the browser is going to expose as a touch event. Time to wait for apple to add this functionality. Thanks!

**Comment by patrickhlauke** [comment]
Thanks for checking. Interesting to know that iOS safari/UIWebView/WKWebView (presumably?) does this sort of palm rejection.
