### ISSUE TITLE
pointerleave is not called after a click in macOS

### ISSUE THREAD

**Issue by shpeled** [jquery/PEP#361]
When listening for a pointerleave event on an element in safari browser on a mac, it will be called as it should. After clicking on the element one time, the poinerleave will not be called again.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
