### ISSUE TITLE
Allow Config Option To Using Capture Phase

### ISSUE THREAD

**Issue by SpencerLynn** [jquery/PEP#363]
It would be nice for a configuration option that would allow events to be polyfilled using the capture phase.

After including the `pep.js` file, one could have:
```
PointerEventsPolyfill.useCapturePhase = true
```

I am willing to investigate doing the work, but wanted to get some thoughts before going further.

**Comment by SpencerLynn** [comment]
It looks like the event listeners are added immediately, so a `reinitialize` function, or something similar, will likely be needed instead of simply setting a a config.

**Comment by SpencerLynn** [comment]
@scottgonzalez Do you happen to know if this would be a welcome change (assuming this library is still maintained)?

**Comment by scottgonzalez** [comment]
The polyfill should work as closely as possible to a native implementation. There should not be flags to control global behavior for the polyfill. Can you expand upon what exactly you're trying to accomplish?

*Note: We are looking for new maintainers. I am no longer actively maintaining this project but have been unable to find someone available to take over as lead.*

**Comment by SpencerLynn** [comment]
There seems to be a scenario, in which you can prevent an element from firing pointer events. In browsers that support native pointer events, the `pointerdown` event is still fired even if `mousedown` event has propagation stopped.

However, in Safari, while using PEP, if I `preventDefault()` on the `mousedown` event, then no `pointerdown` event is fired. This is one reason to use `capture`. Perhaps this should just be the default?

Here are code-pen where the issue is present:
Native Pointer Events: https://codepen.io/spencerlynn/pen/eKdprG
Polyfilled Pointer Events: https://codepen.io/spencerlynn/pen/xzEwjz

**Comment by IanBellomy** [comment]
@spencerlynn sorry if this changed in an update since your post, but is it not possible to specify capture when you add the event listener?

**Comment by SpencerLynn** [comment]
@IanBellomy The event listeners are added by the library itself - not the consumer of PEP.

**Comment by IanBellomy** [comment]
@SpencerLynn Apologies, I think I was confused because Safari (at least) will call capture handlers in expected order for custom events dispatched from an element, including those events created by PEP. i.e. I've been using PEP in mobile Safari for both capture and bubbling phases.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
