### ISSUE TITLE
Comment about "Support: Firefox <=44 only" seems to be wrong

### ISSUE THREAD

**Issue by camilledalmeras** [jquery/PEP#371]
Hello maintainers,

Pointerup events ceased to be detected on desktop Safari and on Chrome 49 (with more versions probably affected) once I deleted the following code on the faith that I would not be needing it:

        // Support: Firefox <=44 only
        // FF Ubuntu includes the lifted button in the `buttons` property on
        // mouseup.
        // https://bugzilla.mozilla.org/show_bug.cgi?id=1223366
        e.buttons &= ~BUTTON_TO_BUTTONS[e.button];
        if (e.buttons === 0) {
          dispatcher.up(e);
        } else {
          dispatcher.move(e);
        }

I have a hunch this may be the root cause of issue #352.
Crude test case below, with the whole of pep.js as an inline script and the aforementioned snippet commented out.
Thanks.

[bug.txt](https://github.com/jquery/PEP/files/2341302/bug.txt)

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
