### ISSUE TITLE
Missing install / import instructions

### ISSUE THREAD

**Issue by jmeyers91** [jquery/PEP#374]
It seems the only examples in the readme involve either downloading the `dist.js` file (from the repo I guess) or using the CDN. All of my other dependencies are available through npm and I can `import` them directly, but the [pep package on npm](https://www.npmjs.com/package/pep) isn't related to this, and it's not clear in the readme if the dist can be imported properly.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
