### ISSUE TITLE
Doesn't work in iOS safari web view (Cordova)

### ISSUE THREAD

**Issue by jmeyers91** [jquery/PEP#375]
I'm trying to get pointer events working in a Cordova app that targets Android and iOS. On iOS, pointer events don't seem to work at all regardless of whether or not I include this polyfill. This is my test code (run after `deviceready` is fired):

```js
const pressEl = document.querySelector('#press-el');

pressEl.addEventListener('pointerdown', event => {
  console.log('pointerdown');
});

pressEl.addEventListener('pointerup', event => {
  console.log('pointerup');
});
```

No matter how many times I press the element `#press-el`, nothing ever gets logged.

Here is the minimal test project: https://github.com/jmeyers91/cordova-pep-ios

EDIT: After a bit more searching, I came across [points](https://github.com/Rich-Harris/Points) another pointer event polyfill that seems to work perfectly in this test project.

**Comment by pal03377** [comment]
I'm no expert in this, but when I read the README file of this repo I found that maybe you are missing the `touch-action` attribute?
https://github.com/jquery/PEP#touch-action

You don't seem to have it here: https://github.com/jmeyers91/cordova-pep-ios/blob/master/www/index.html

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
