### ISSUE TITLE
PointerEvent clientX and clientY are long instead of double in Safari IOS

### ISSUE THREAD

**Issue by ystreibel** [jquery/PEP#380]
Hi,

For PointerEvent properties clientX and clientY values are long integer instead of double in Safari IOS.

PEP as a Polyfill should handle this ? No ?

PointerEvent clientX and clientY came from MouseEvent inheritance.

Mozilla Developer Network (MDN) docs definitions:

- [clientX](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX)

    Pointer.clientXEvent => MouseEvent.clientX Read only

    The X coordinate of the mouse pointer in local (DOM content) coordinates.
    The clientX read-only property of the MouseEvent interface provides the horizontal coordinate within the application’s client area at which the event occurred (as opposed to the coordinate within the page).
    A double floating point value, as redefined by the CSSOM View Module. Originally, this property was defined as a long integer. See the “Browser compatibility” section for details.

- [clientY](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientY)

    PointerEvent.clientY => MouseEvent.clientY Read only

    The Y coordinate of the mouse pointer in local (DOM content) coordinates.
    The clientY read-only property of the MouseEvent interface provides the vertical coordinate within the application’s client area at which the event occurred (as opposed to the coordinate within the page).
    A double floating point value, as redefined by the CSSOM View Module. Originally, this property was defined as a long integer. See the “Browser compatibility” section for details.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
