### ISSUE TITLE
Invalid ES5 Code

### ISSUE THREAD

**Issue by pladaria** [jquery/PEP#384]
In [this file](https://github.com/jquery/PEP/blob/49bea4515f4fced1c4fef5e29652b2918374da5c/src/touch.js#L173) keyword `const` is used:

```javascript
    if (inTouch.altitudeAngle) {
      const tan = Math.tan(inTouch.altitudeAngle);
      const radToDeg = 180 / Math.PI;
      e.tiltX = Math.atan(Math.cos(inTouch.azimuthAngle) / tan) * radToDeg;
      e.tiltY = Math.atan(Math.sin(inTouch.azimuthAngle) / tan) * radToDeg;
    } else {
```
And that goes to the bundle:
![Selección_007](https://user-images.githubusercontent.com/579417/60259797-58b31500-98d8-11e9-8cc2-d01a8dce7045.png)

This can cause problems in older browsers

**Comment by dmethvin** [comment]
Great catch! I think ESLint can check for these if we tell it what version of JavaScript we are targeting. Could you take a look at what we need to do in order to enable that?

**Comment by Orange-J** [comment]
The keyword `const` should be transpiled to `var`.

**Comment by bertho-zero** [comment]
You can now use [@openagenda/pepjs](https://www.npmjs.com/package/@openagenda/pepjs).
