### ISSUE TITLE
Please publish a new version without const !

### ISSUE THREAD

**Issue by bertho-zero** [jquery/PEP#390]

**Comment by bertho-zero** [comment]
You can now use [@openagenda/pepjs](https://www.npmjs.com/package/@openagenda/pepjs).

**Comment by apptaro** [comment]
Just a note, here's the 'const' he is talking about:
https://github.com/jquery/PEP/blob/master/src/touch.js#L173

pepjs doesn't work on old browsers like iOS 9 Safari.
