### ISSUE TITLE
Sometimes PEP attempts to create shadow root on unloaded document and fails 

### ISSUE THREAD

**Issue by alexkonstantinovakvelon** [jquery/PEP#391]
I'm using pep inside safari extension and observe sometimes observe an error in console `TypeError: null is not an object (evaluating 'document.head.createShadowRoot')` when PEP attempts to instantiate shadow root when document has not header yet.

Is it possible to update the logic to instantiate shadow root only when document uploaded and has a head?

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
