### ISSUE TITLE
[Questions] : 0.5.1

### ISSUE THREAD

**Issue by jeremyVignelles** [jquery/PEP#396]
This version was released more that 1 year ago, but I don't find any info about what the changes were since the 0.4.3, which is still [declared as the latest release](https://github.com/jquery/PEP/releases) and is still used in [the README](https://github.com/jquery/PEP/blob/master/README.md).

Should I use 0.5.1 ?

**Comment by patrickhlauke** [comment]
unless you need to support old versions of iOS or IE<11 ... i'd say just don't use it at all. this has been broken and unmaintained for aeons, and now not needed anymore since modern versions of iOS support pointer events.

**Comment by patrickhlauke** [comment]
https://caniuse.com/#feat=pointer

(forgot about firefox for android and a few other outliers)

**Comment by jeremyVignelles** [comment]
I need it for firefox mobile (current android stable), which I'm using as my main browser.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
