### ISSUE TITLE
offsetX, offsetY are not correct in Firefox, Opera, Chrome mobile

### ISSUE THREAD

**Issue by dylang** [jquery/PEP#41]
When pointerevents fire the only way to get the location relative to the target element is `offsetX` and `offsetY`. 

These values appear to be `0` in some browsers.

Working correctly:
* Firefox for desktop
* Safari for desktop

Wrong values:
* Chrome beta for Android

Always zero:
* Firefox
* Opera

Not tested:
* Any IE
* Mobile Safari

**Comment by jacobrossi** [comment]
Actually, this is standardized in CSS OM View: http://www.w3.org/TR/cssom-view/#extensions-to-the-mouseevent-interface 

We should add these as they're very helpful.

**Comment by arschmitz** [comment]
Agreed we should fix this i'm going to re open this issue

**Comment by patrickhlauke** [comment]
I believe Firefox only recently implemented these? https://bugzilla.mozilla.org/show_bug.cgi?id=69787

**Comment by arschmitz** [comment]
These have worked in firefox for a long time. We have used them in the jQuery Mobile swipe events for years and you can see in the original issue above the reporter says firefox is working correctly. 

However there are some browser issues we work around with them in jQuery Mobile https://github.com/jquery/jquery-mobile/blob/master/js/events/touch.js#L117-L142

**Comment by arschmitz** [comment]
@patrickhlauke Hmm that bug thread does sound that way though, and re reading the description they say works fine firefox desktop, but below for just "firefox" it says always zero. This is very confusing...

**Comment by jzaefferer** [comment]
While this ticket is older, #217 has pretty much the same discussion and a potential solution. Closing this as a duplicate.
